"""Original long-form copy, grounded in the profile reviewed on 6 October 2026."""
def populate(add,sec,PROFILE):
 courses=[
 ('sales','Sales Fundamentals for Entrepreneurs','LinkedIn Learning','July 2026','Business','https://www.linkedin.com/learning/certificates/df10c19e671351a32002e9151bb17200b70d64f4c6d8ff0494e88b633529c6b2/','',[
  sec('Understanding the customer side of a business','I completed Sales Fundamentals for Entrepreneurs with LinkedIn Learning in July 2026. It introduced me to sales operations and the customer side of a business. Alongside my administration, finance, and resilience courses, it gave me another way to think about how an organisation turns an idea into something people want to use.','Understanding a business means understanding its customers. A product can be technically impressive, but I also want to ask whose problem it solves and why someone would choose it. That customer perspective is useful for my interest in corporate and commercial law, because it puts the business purpose behind an announcement into focus.'),
  sec('Questions I want to investigate','I want to become better at asking what a business offers, who it is intended for, and why someone would choose it. Those questions can make a company announcement more useful to analyse. They shift attention from the excitement around a product to the assumptions on which its adoption depends.','My reflections on technology events provide a starting point for that habit. Demonstrations show a capability; the harder question is what makes it practical in a real setting. Sales learning adds a customer perspective to that question, alongside the operational and technical perspectives I have encountered elsewhere.'),
  sec('A practical next step','I want to try analysing a public product launch through those questions. Who is it for? What value does the company promise? What remains unclear? Writing a short explanation would help me connect the course to something concrete, while giving me a reason to look more closely at the information behind the launch.','A certificate marks the end of a course, but it need not be the end of the subject. I want to use the ideas in my commercial reading: checking what a company says, finding out what it has actually shown, and explaining why the difference matters to someone considering the product.')]),
 ('resilience','Resilience: Thriving as an Entrepreneur','LinkedIn Learning','July 2026','Business','https://www.linkedin.com/learning/certificates/065eb6d0baaaccd42b267cc5b95e29146b829d023d0e6acc5967c42a0a126d9e/','',[
  sec('Learning to respond to a setback','I completed Resilience: Thriving as an Entrepreneur with LinkedIn Learning in July 2026. What stayed with me was the idea that resilience can be practised: focus on what you can control, adapt when a plan changes, and learn from a setback instead of treating it as the end of the story.','That perspective is relevant to my current stage as a student. Academic progress and career research involve uncertainty, and a plan may need revision as better information becomes available. The useful response is to identify the next action, learn from what happened, and avoid turning one outcome into a judgement about the entire journey.'),
  sec('Progress that can be repeated','My post also mentioned small wins and personal well-being. These ideas matter because a long-term goal depends on habits that can be maintained. A dramatic burst of effort may feel productive, but the question I want to ask is whether the approach will support the next week of work as well.','I can apply that thinking to school and career planning now. A difficult task may need a different method, a missing piece of information, or another attempt. I want to become better at noticing which of those would actually help, rather than letting frustration decide what I do next.'),
  sec('Connecting the lesson to my direction','My ambition in corporate law requires preparation over time. Academic work, understanding the profession, and researching education routes are different tasks, and none becomes complete because the ambition is clear. The resilience theme encourages me to focus on the part of the process I can improve now.','A practical next step is to review a difficult task by asking what was within my control, what information I lacked, and what I would change in the next attempt. That turns an abstract lesson into a method of reflection, while keeping the conclusion grounded in actual experience.')]),
 ('business-administration','Diploma in Business Administration','Alison','December 2024','Business','https://alison.com/verify/658694076c','3038-36834668',[
  sec('The organisation behind an outcome',"I completed Alison's Diploma in Business Administration in December 2024. The course introduced an organisational perspective to my learning: how information, people, and processes contribute to an outcome. My certificate is linked below, and the credential ID is 3038-36834668.",'The course belongs to my interest in how organisations function. A visible result depends on information, people, processes, and communication coming together. Business administration gives introductory context for that wider picture and complements the operational questions that first interested me through aviation.'),
  sec('Why administration interests me','Administrative work can be easy to overlook when everything is running smoothly. Yet the way information is organised and communicated affects what a team can do next. I want to understand those connections more clearly: who needs which information, when it is needed, and how an unclear process can create avoidable friction.','My school volunteering provides a practical point of connection. Event coordination, guest seating, setup, and backstage support involved contributing to a programme larger than any single task. That experience was not business employment, but it made the importance of organisation and clear responsibilities tangible.'),
  sec('Relevance to future study','My current interest in corporate law gives this introductory business learning another purpose. I want to understand a company as an organisation before trying to interpret the issues around it. A business has objectives, customers, internal processes, and constraints; learning to ask about those elements is part of building commercial awareness.','I want to build on the course through reading and practical experience. My interest in law makes me curious about what a company needs in order to work well, beyond the announcement or product everyone sees. Understanding that everyday organisation gives me a better starting point for the more detailed questions ahead.')]),
 ('business-finance','Introduction to Business Finance','Alison','October 2025','Business','https://alison.com/verify/640283d4a4','3998-36834668',[
  sec('An introduction to the financial perspective','I completed Introduction to Business Finance with Alison in October 2025, with credential ID 3998-36834668. The course covered the history and principles of business finance and introduced investment analysis tools. It added a financial perspective to the organisational questions I had already begun exploring through business administration.',"Finance interests me because a business decision has assumptions behind it. What is expected to create value? What could change the outcome? How does the decision fit the organisation's purpose? Those questions help me read about a transaction with more attention to its reasoning, instead of stopping at the headline."),
  sec('Questions beyond a headline','When reading about a company or investment, I want to ask what the business is trying to achieve and which assumptions support the decision. What is expected to create value? Which uncertainties might change the outcome? What information would a reader need before reaching a stronger conclusion?','M&A and private equity are the areas I particularly want to explore. I am curious about how commercial, financial, and legal perspectives come together, and how people deal with uncertainty. I am still building that understanding, beginning with introductory learning and a more careful approach to reading about businesses.'),
  sec('Building a useful foundation','Administration and finance let me look at a business from two connected angles: how it works and how it makes decisions about value and resources. I want to become more comfortable explaining that connection in plain language. When I cannot explain something clearly, it helps me see what I need to investigate next.',"I would like to follow one public business development over time, beginning with the company's stated aim and watching what happens afterwards. Which assumptions become clearer? Which questions remain? That would give me a practical way to develop my reading and connect introductory finance ideas to an actual commercial story.")]),
 ('aircraft-design','Introduction to Aircraft Design','Alison','May 2025','Aviation','https://alison.com/verify/f1e8c7db59','3071-36834668',[
  sec('A design perspective on aviation','I completed Introduction to Aircraft Design with Alison in May 2025. It explored aircraft design procedures and technology, and its credential ID is 3071-36834668. The course followed my interest in aviation and gave me a way to think about the decisions behind something I had previously understood mainly as a finished aircraft.','At the time, aviation was the career I wanted to pursue. I enjoyed having a structured introduction to a subject that had already caught my attention outside school. Looking at design made me ask more questions about requirements, constraints, and how several choices affect the same result.'),
  sec('Looking at a system as a whole','Design invites questions about how individual choices affect the whole. Rather than treating an aircraft as one object, I want to understand how different components, requirements, and constraints are considered together. That wider way of looking at a problem is one reason aviation held my attention.','That habit of looking at connections still matters to me. An organisation or a transaction also needs to be understood in its wider setting, even though the details are very different. I want to keep the curiosity I had about aviation while finding new ways to use it in my commercial reading.'),
  sec('Questions I want to keep asking','The course gave me a starting point for further questions. I want to be able to explain a design choice in clear terms: what problem it addresses, what it depends on, and what information I would need to understand it better. That is the kind of attention I want to develop across technical subjects.','A useful next exercise would be to choose one design question and explain it to someone unfamiliar with aviation. Keeping the language simple would make me think more carefully about the idea itself. I would need to identify what I understand, check the unfamiliar parts, and show how the choice fits the wider aircraft.')]),
 ('aviation-management','Basics of Aviation Management','Alison','March 2024','Aviation','https://alison.com/verify/cc4ec37d25','6052-36834668',[
  sec('The wider operation around a flight','I completed Basics of Aviation Management with Alison in March 2024, with credential ID 6052-36834668. The course introduced flight operations, airport security, and risks. It helped me look beyond the aircraft towards the organisation around a flight, and became one of my first structured steps into learning about aviation.','The Global Airports Forum later made those questions more tangible. A small boarding delay can affect gate availability, crew time, aircraft rotations, baggage, and wider coordination. I became interested in how an operation that feels straightforward to a passenger depends on many people understanding what needs to happen next.'),
  sec('Coordination as a recurring theme','The question that interests me is how many individual decisions contribute to a result that feels straightforward to the person using it. A passenger may notice whether a journey runs smoothly; understanding the operation requires looking at the work behind that experience.','That theme also connects to my practical school volunteering. A graduation programme depends on setup, seating, logistics, staff support, and backstage activity. The settings are very different, but both encourage attention to responsibilities and the flow of information between people.'),
  sec('An early interest that still matters','My intended career has moved towards corporate and commercial law, but aviation still helps explain what interests me. I like understanding how an organisation delivers its service, what people need from one another, and how decisions affect the whole. The course gave me an early way to approach those questions.','The next useful step is to revisit the operational questions through a broader commercial perspective: what an organisation needs to deliver its service, how it plans, and how decisions affect the wider system. Further study and practical experience would be needed before drawing specialist conclusions about aviation operations.')]),
 ('crew-management','Crew Management on Multi-Pilot Aircraft','Alison','January 2024','Aviation','https://alison.com/certification/check/2y10MjgCMik9bOBpRxHAjte8mp7VozAs2192PrAxkYWLGKyTYqa62','AC-5337-36834668',[
  sec('An early structured step','I completed Crew Management on Multi-Pilot Aircraft with Alison in January 2024. Its credential ID is AC-5337-36834668. It was one of my first independent courses and followed my interest in aviation, especially the communication and coordination behind an operation that can look effortless from the outside.','The course appealed to me because its setting depends on people working towards a shared outcome. I wanted to understand how they communicate, recognise uncertainty, and keep track of the situation together. Those questions made aviation interesting as a system involving people, not simply a collection of aircraft.'),
  sec('Communication and shared understanding','One useful question to carry from crew management learning is how people build a shared understanding of a situation. Who has the relevant information? How is uncertainty communicated? What happens when an assumption is left unstated? Those questions make communication more than simply passing on a message.','I have since noticed related questions in school volunteering and business learning. When several people contribute to one programme, understanding the immediate task and its purpose matters. The settings are different, but each makes me think about what someone needs to know in order to contribute well.'),
  sec('What I carried forward','Communication is the idea I keep returning to from this course. Who has the important information? How is an uncertainty raised? What happens when people make different assumptions about the same task? Those are questions I want to practise asking in teamwork, and later in the professional settings I hope to learn about.','I would like to get better at reviewing a teamwork experience: what made the task clear, what was confusing, and which information helped people move forward. That gives me something practical to improve. It also makes communication feel like a habit I can work on, rather than a label I attach to myself.')])
 ]
 for name,title,provider,date,tag,url,credential,sections in courses:
  sections.append(sec('My course certificate',"I completed this course alongside my school studies. You can open the certificate below to see the provider's details and credential information. What interests me now is how to build on the introduction: reading further, checking my understanding, and finding useful connections to my other learning."))
  add('learning/'+name+'.html',title,'Learning',title+' — completed with '+provider+' in '+date+'. What I learned and how it connects to my interests.',sections,date=date,label=provider+' · '+date,tags=tag.lower(),source=url,source_label='View my certificate',source_note='My course certificate',source_description='You can open the certificate below to see the course and provider details.',facts=[('Provider',provider),('Completed',date),('Learning','Course completion'),('Credential ID',credential or 'View certificate below')],related=['learning.html','skills/business.html' if tag=='Business' else 'skills/systems.html','direction.html'])

 add('skills/business.html','Understanding the business first.','Skills','Administration, finance, sales, entrepreneurship, and resilience as an introductory commercial foundation.',[
  sec('How I began learning about business','I have studied business administration and finance with Alison, and sales and entrepreneurial resilience with LinkedIn Learning. Together, those courses made me curious about how a business works from the inside: the organisation, the customer, the decisions about money, and the ability to adapt when plans change.','I am using that learning as a foundation. I want to become more comfortable reading about companies, understanding the purpose behind an announcement, and explaining the questions it raises. Each subject adds a different angle, and I enjoy seeing where they connect rather than treating them as separate course titles.'),
  sec('Different views of one organisation','Administration asks how the work is organised. Finance adds questions about objectives, information, and the assumptions around a commercial decision. Sales adds the customer perspective: who the business serves and how it communicates value. Resilience focuses attention on responding when a plan does not unfold as expected.','I want to become better at connecting those perspectives when I read about a company. A headline rarely tells the entire story. Understanding what a business is trying to do, what it depends on, and which uncertainties remain is a more useful starting point for analysis.'),
  sec('Connection to corporate law','My ambition is corporate and commercial law, especially M&A and private equity. Learning about business gives me a starting point for that ambition. Before studying the legal detail around a decision, I want to understand what the organisation is trying to do, who it serves, and what it depends on.','Those questions are what draw me towards transactions. A decision can make sense from one angle and look more complicated from another. I want to understand how people bring the commercial, financial, and legal perspectives together, and how they decide which uncertainties need more attention before moving forward.'),
  sec('What I want to try next',"I would like to write a short reading note about a public business development. I would begin with the company's objective, look at the information available, and set out the questions I still have. Explaining it simply would help me notice where my understanding is clear and where I need to read further.",'The point is to use what I have learned, then keep building on it. I want future experiences to help me understand the everyday work behind an organisation, not just the vocabulary used to describe it. Better reading, clearer writing, and suitable practical opportunities are the next steps I am interested in.')
 ],related=['learning/business-administration.html','learning/business-finance.html','direction/transactions.html'])
 add('skills/communication.html','Clarity is a form of responsibility.','Skills','Communication through volunteering, multilingual development, and public reflection.',[
  sec('A practical example','At the AIS graduation ceremony in May 2025, I helped with event coordination, guest seating, logistics, setup, attendee guidance, and backstage operations. My role was Student Volunteer. Those duties involved supporting staff and students as part of a wider programme.','Communication felt practical at the graduation ceremony. An attendee needed the right guidance, staff needed support, and each task had to fit the flow of the event. Helping with those things made me pay attention to what someone actually needs to know, and whether my explanation makes the next step easier.'),
  sec('Making sense of an experience through writing','I enjoy writing about what I notice at aviation, technology, business, and governance events. Putting an experience into words makes me ask why it stayed with me. I want the reader to understand the idea that mattered, rather than have to work through a list of things I saw.','Writing gives me a different way to practise clarity. I want a reflection to explain what I noticed and why it mattered, without making the reader work through unnecessary phrasing. The journal lets me return to those ideas and develop them, while the original posts show where the thought began.'),
  sec('Language and listening','Languages are another part of how I communicate. Urdu and Punjabi are my native languages, and I speak Hindi fluently. I use English for my studies and writing, have a limited working knowledge of Arabic, and am beginning French, German, and Korean. Each language needs a different kind of attention from me.','After the UNESCO forum I wrote about the value of conversations with people from different countries and backgrounds. Listening to different perspectives can reveal how much context sits behind a position. I want to develop that attention alongside my ability to express my own ideas.'),
  sec('A continuing development priority','Clear communication is something I want to carry into legal study. I am interested in explaining a difficult idea accurately and understanding the person I am speaking to. Volunteering and writing have given me places to practise, and I want to keep improving through work that requires patience and careful wording.','I want more practice with tasks that test whether an explanation is useful: summarising a complicated subject, asking a focused question, or helping someone understand what to do next. It is worth noticing when something was unclear, because that gives me a more specific improvement to make the next time.')
 ],related=['experience/graduation.html','languages.html','journal.html'])
 add('skills/systems.html','Looking behind the visible result.','Skills','An interest in systems shaped by Computer Science, aviation learning, and technology events.',[
  sec('Where the interest comes from','I study Computer Science alongside Mathematics and Physics at International A Level. Outside school, aviation courses and events helped me become interested in how separate components, people, and decisions contribute to one outcome. My later technology reflections extend that interest into AI, cybersecurity, identity, and business.','Systems thinking, for me, means looking at what connects an outcome to the work behind it. A smooth journey, a reliable service, or a convincing demonstration depends on other things happening well. I want to get into the habit of asking about those connections before assuming that the visible result tells the whole story.'),
  sec('The airport example','In my Global Airports Forum post, I described how a short boarding delay can connect to gate availability, crew duty time, aircraft rotations, baggage, and wider coordination. The observation changed how I looked at something that can appear simple from the passenger’s perspective.','The useful habit is to ask what dependencies sit behind an outcome. Which teams need to coordinate? Which information arrives at the right time? What happens when one assumption changes? These questions encourage a more careful account of a system without pretending to have operational expertise.'),
  sec('The technology example','At Money20/20, I wrote about AI agents and questions of identity and authorisation. At the UNESCO forum, I focused on responsibility and governance. Those experiences shifted my attention from what technology can demonstrate to what organisations need before they can rely on it.','That distinction is relevant to my current commercial interests. A business adopting a new tool has more to consider than a feature list. I want to understand the human, organisational, and technical context around the decision, while recognising that specialist conclusions require deeper knowledge.'),
  sec('Applying the habit carefully','This website gives me a small example of those connections. The writing, navigation, reading modes, and animations need to work together so that someone can follow an interest. I wanted the movement to support the story and the links to make the next step clear, especially on a smaller screen.','I want to bring that attention into my research and writing. What depends on what? Which assumption matters? What would change the result? A clear answer to one of those questions is more useful to me than a broad description of a subject. It gives me something concrete to understand and explain.')
 ],related=['events/airports.html','events/money2020.html','projects/portfolio.html'])

 language_groups=[
 ('established','Languages rooted in my background.','Urdu and Punjabi are my native languages; I speak Hindi fluently.',[
  sec('The languages I know best','Urdu and Punjabi are my native languages, and I speak Hindi fluently. They form the most established part of my language background. I think of them differently from the languages I am still beginning: the starting point is familiarity, and the next question is how well I can express a particular idea.','I am interested in how meaning changes with the words someone chooses. Even in a familiar language, tone and context matter. An everyday explanation, a formal message, and a discussion about an unfamiliar subject each need different wording. Knowing a language well gives me a starting point, but attention to the person still matters.'),
  sec('A background with more than one language','Being a Pakistani student in Saudi Arabia puts several languages around my life and education. Urdu, Punjabi, and Hindi sit alongside the English I use for schoolwork and public writing, and the Arabic I am developing in Riyadh. I enjoy the different perspectives that come with that background, including the way an idea can be expressed differently.','Speaking more than one language makes me interested in phrasing. A sentence can be accurate and still sound distant, or simple and still lose something important. I want to become better at finding wording that keeps the meaning and feels natural to the person reading or listening. That is a skill I can keep developing.'),
  sec('Choosing the right words','Familiarity is especially useful when I need to focus on an idea instead of searching for a word. Still, a new subject brings its own vocabulary. Legal, technical, and academic discussions ask for more care than an everyday conversation, and I want to learn that vocabulary properly as my studies become more demanding.','For me, good communication begins with understanding what the other person needs. Sometimes that is a direct answer; sometimes it is a slower explanation with a little more context. I want to be comfortable changing the way I explain something while keeping the underlying meaning clear and accurate.'),
  sec('What I want to improve','Urdu, Punjabi, and Hindi are only part of my language background. English and Arabic have a different place in my current setting, while French, German, and Korean are still at the beginning. I find it useful to recognise those different starting points, because each suggests a different kind of practice and patience.','I want to keep improving the quality of my communication across all of them. That means listening carefully, noticing when a phrase is unclear, and becoming more precise in my writing. The aim is not simply to know another language name; it is to understand someone better and make my own meaning easier to follow.')]),
 ('working','Communication across my current setting.','English for my studies and writing, and Arabic as a language I am continuing to develop.',[
  sec('Two languages, different stages','I use English for my studies, public writing, and professional communication. My Arabic is still developing, and I have a limited working knowledge of it. The two have different places in my life: English supports my academic work, while Arabic connects to living in Riyadh and understanding the setting around me.','I noted an English Duolingo score of 130 in December 2025 as part of my learning. It is not a formal exam result. What matters more to me is whether I can follow a difficult explanation, make my own argument clear, and choose wording that fits the subject and the reader.'),
  sec('English in academic and public writing','Schoolwork gives me a reason to use English with precision, and public writing gives me room to practise expression. I want to be able to explain why something caught my attention, rather than simply say that it was interesting. Returning to a draft often helps me see which part of the thought needs more work.','I want my writing to become clearer and more deliberate. That includes organising an argument, choosing the information that matters, and explaining an unfamiliar subject without burying the main point. Those habits are relevant to my interest in law, and they are things I can start practising through my studies and reflections now.'),
  sec('Arabic in the place I live','Living in Riyadh gives Arabic a particular relevance for me. I have a limited working knowledge of it, and there is more I want to learn. I want to become more comfortable understanding the language in its setting, while taking the time to ask for clarification when a phrase or topic is unfamiliar.','Learning a language involves being willing to slow down. I want to notice what I have understood, what I have assumed, and where I need help. That applies to English too: a familiar language can still make a difficult subject challenging. Asking a clear question is often more useful than pretending an explanation was straightforward.'),
  sec('Learning through practice','I want to keep improving through specific tasks: writing a clearer paragraph, understanding an explanation more closely, or choosing a better way to express a question. A broad proficiency level can describe a starting point, but it is the practical work that helps me see what is becoming easier and what still needs attention.','English and Arabic sit alongside my established languages and my early learning in French, German, and Korean. I enjoy seeing the connections between them, but I also know that each needs its own practice. The aim is more useful communication: understanding the situation, listening carefully, and expressing what I mean with greater confidence.')]),
 ('exploring','At the beginning of three languages.','I am beginning to learn French, German, and Korean.',[
  sec('Beginning again as a learner','I am a beginner in French, German, and Korean. There is still plenty of unfamiliar vocabulary and phrasing, and I think of these as languages I am beginning rather than languages I already know well. I enjoy having an interest that asks me to be patient with the basics.','Starting a language reminds me that recognition and understanding are different. A familiar word might make a sentence easier to approach without making the whole meaning clear. I want to keep noticing that difference and build gradually, becoming more comfortable with the small pieces before expecting a difficult conversation to feel natural.'),
  sec('An early German milestone','I recorded a German Duolingo score of 10 in April 2025 as a learning milestone. It belongs to an early stage of my interest in the language. I keep it separate from formal examinations, because an app score and the ability to understand a particular conversation tell me different things.','My German is still at a beginner stage. I would like the next steps to make a practical difference: recognising more phrasing, following an explanation more easily, and finding better ways to express a simple thought. Each of those would matter more to me than attaching a stronger label too early.'),
  sec('Making room to be a beginner','These languages give me room to be a beginner alongside the ones I know better. That is a useful reminder when learning any subject. I can be interested in something before I understand it well, and I can make progress without expecting every attempt to feel fluent or effortless.','I want to pay attention to the different parts of language learning. Recognising a word on a page is not the same as hearing it in speech, and understanding an explanation is not the same as being able to give one. Noticing which task is difficult helps me work on a more specific next step.'),
  sec('A practical development perspective','My wider interest is in how people express meaning. Beginning a new language makes that more noticeable: the order of a sentence, the tone of a phrase, or the difference between a literal explanation and a natural one. I want that curiosity to make me more attentive in the languages I already use too.','French, German, and Korean complete the language picture alongside Urdu, Punjabi, Hindi, English, and Arabic. They are at a different stage, and I am comfortable saying that. I want the learning to remain enjoyable while becoming more useful, with better understanding, a little more confidence, and patience for the parts that take longer.')])]
 for name,title,desc,sections in language_groups:
  add('languages/'+name+'.html',title,'Languages',desc,sections,source=PROFILE+'details/languages/',source_label='Connect with me',related=['languages.html','skills/communication.html','about.html'])

 add('direction/transactions.html','Interested in the decision behind the deal.','Direction','The questions drawing me towards mergers, acquisitions, and private equity.',[
  sec('An area I want to understand','Mergers and acquisitions and private equity are specific interests of mine. They sit within a broader ambition to pursue corporate and commercial law. I am interested in how a business decision is understood from several perspectives and how the people involved work through uncertainty.','I am approaching transactions as a student with questions to explore. I want to understand what a business hopes to achieve, how people investigate the details, and what makes a decision more complicated than its announcement suggests. That gives me a direction for reading while I prepare for future legal study.'),
  sec('Beginning with the commercial purpose','The first question I want to investigate is what a business hopes to achieve. Why pursue a transaction? What would success look like? Which assumptions does the decision depend on? Looking at the stated purpose gives a student a more useful starting point than trying to memorise a deal headline.','My introductory finance and administration courses help me ask about the organisation and its objectives. I am interested in the connection between those questions and the legal work around a deal. A clearer understanding of the business should make the unfamiliar parts easier to approach when I study them in more depth.'),
  sec('Information, uncertainty, and responsibility','Another area I want to understand is how decision-makers establish what they need to know. Which information would change their view? Where is uncertainty accepted, reduced, or left open? Who needs to understand the consequences before the next step is taken?','These questions connect to themes in my other learning. Aviation introduced coordination; technology events introduced implementation and accountability. The subjects differ, but each encourages attention to the system around an outcome rather than only the visible result.'),
  sec('A realistic development plan','I would like to follow a public transaction announcement and write down its purpose, the information I can find, and the questions I still have. That would give me a concrete task to practise commercial reading. I could return to it later and see how the story changed as more information became available.','I want to develop that understanding through work: read carefully, explain the reasoning, and learn where I need a better explanation. Future legal study and practical experience will add another layer. For now, I can make progress by being specific about the question and taking the time to understand the answer.')
 ],related=['learning/business-finance.html','skills/business.html','direction.html'])
 add('direction/technology.html','Technology creates responsibilities.','Direction','AI governance, identity, and cybersecurity as questions for a developing commercial perspective.',[
  sec('A different view of innovation','My interest in technology has grown through Computer Science study and events in Riyadh. LEAP made emerging products tangible. Black Hat MEA introduced another view through cybersecurity. Money20/20 drew my attention to identity and authorisation, while the UNESCO forum shifted the conversation towards accountability and governance.','The connection to my current legal ambition is the set of questions these experiences create. I want to understand how a business can use a technology and what responsibilities follow from relying on it. These are student learning questions, not legal opinions.'),
  sec('Capability is only the first question','A demonstration can show that a system performs a task. My Money20/20 reflection asks what is needed before organisations can rely on that capability in use. Identity, security, reliability, and infrastructure were the themes that stood out to me.','AI agents made the question particularly concrete: if a system takes an action for a person, how is authorisation established and how much control remains with that person? I want to examine such questions carefully without assuming that a conference discussion settles the answer.'),
  sec('Responsibility and perspective','At the UNESCO forum, I wrote about who is responsible when AI causes harm, how human accountability is maintained, and how different countries approach governance. Conversations with people from different backgrounds added to that perspective.','The experience made me interested in implementation as well as principles. How is a broad goal translated into an actual process? Who needs to understand it? What information would show that the process is working? Those questions connect technology to the wider organisation around it.'),
  sec('Where I want to take this interest','My next step is stronger research and clearer writing. I want to distinguish product claims from demonstrated use, a policy ambition from its implementation, and my own interpretation from a sourced fact. The journal is a place to practise that distinction.','Technology gives me another route into the business questions that interest me. I want to understand how an organisation decides to rely on a new system, what people need from it, and how responsibility is handled. Further reading and experience should help me move from a broad curiosity to a more precise understanding.')
 ],related=['events/unesco.html','events/money2020.html','journal/ai-governance.html'])
