"""Original long-form copy, grounded in the profile reviewed on 6 October 2026."""
def populate(add,sec,PROFILE):
 courses=[
 ('sales','Sales Fundamentals for Entrepreneurs','LinkedIn Learning','July 2026','Business','https://www.linkedin.com/learning/certificates/df10c19e671351a32002e9151bb17200b70d64f4c6d8ff0494e88b633529c6b2/','',[
  sec('Understanding the customer side of a business','My profile records completion of Sales Fundamentals for Entrepreneurs, issued by LinkedIn in July 2026. Sales Operations is the associated skill. The course sits alongside my business administration, finance, and resilience learning, giving another angle on how an organisation turns an idea into something people will choose to use.','For my current interest in corporate and commercial law, understanding a business should include understanding its customers. A product may be technically impressive, but the commercial question is how it meets a need and how that value is communicated. This is introductory learning, not a claim that I have managed a sales team or built a company.'),
  sec('Questions I want to investigate','I want to become better at asking what a business offers, who it is intended for, and why someone would choose it. Those questions can make a company announcement more useful to analyse. They shift attention from the excitement around a product to the assumptions on which its adoption depends.','My reflections on technology events provide a starting point for that habit. Demonstrations show a capability; the harder question is what makes it practical in a real setting. Sales learning adds a customer perspective to that question, alongside the operational and technical perspectives I have encountered elsewhere.'),
  sec('A practical next step','A useful exercise would be to examine a public product launch and write a short account of the customer need, the proposed value, and the open questions. That would be a learning exercise rather than a professional market assessment, but it would make the course context more concrete.','The next stage is to support an interpretation with evidence, distinguish a company’s claims from what has been demonstrated, and explain the reasoning clearly. Those are habits I want to develop across my commercial reading, rather than treating a certificate as the end of the subject.')]),
 ('resilience','Resilience: Thriving as an Entrepreneur','LinkedIn Learning','July 2026','Business','https://www.linkedin.com/learning/certificates/065eb6d0baaaccd42b267cc5b95e29146b829d023d0e6acc5967c42a0a126d9e/','',[
  sec('Learning to respond to a setback','My profile records Resilience: Thriving as an Entrepreneur, issued by LinkedIn in July 2026. Entrepreneurship and Business Resilience are the associated skills. In my completion post, I wrote that resilience is a skill to develop and described the value of focusing on what can be controlled, adapting when plans change, and treating failure as feedback.','That perspective is relevant to my current stage as a student. Academic progress and career research involve uncertainty, and a plan may need revision as better information becomes available. The useful response is to identify the next action, learn from what happened, and avoid turning one outcome into a judgement about the entire journey.'),
  sec('Progress that can be repeated','My post also mentioned small wins and personal well-being. These ideas matter because a long-term goal depends on habits that can be maintained. A dramatic burst of effort may feel productive, but the question I want to ask is whether the approach will support the next week of work as well.','I do not present this course as evidence that I have founded or led a business. Its place in the portfolio is more modest and more useful: it records structured learning about a way of responding to challenges. The skills section keeps that course context attached to the labels on my profile.'),
  sec('Connecting the lesson to my direction','My ambition in corporate law requires preparation over time. Academic work, understanding the profession, and researching education routes are different tasks, and none becomes complete because the ambition is clear. The resilience theme encourages me to focus on the part of the process I can improve now.','A practical next step is to review a difficult task by asking what was within my control, what information I lacked, and what I would change in the next attempt. That turns an abstract lesson into a method of reflection, while keeping the conclusion grounded in actual experience.')]),
 ('business-administration','Diploma in Business Administration','Alison','December 2024','Business','https://alison.com/verify/658694076c','3038-36834668',[
  sec('The organisation behind an outcome','My profile records Diploma in Business Administration, issued by Alison in December 2024. The listed credential ID is 3038-36834668, and Business Administration is the associated skill. The same course also appears in my honours section, so it is represented here as one course rather than counted twice.','The course belongs to my interest in how organisations function. A visible result depends on information, people, processes, and communication coming together. Business administration gives introductory context for that wider picture and complements the operational questions that first interested me through aviation.'),
  sec('Why administration interests me','Administrative work can be easy to overlook when everything is running smoothly. Yet the way information is organised and communicated affects what a team can do next. I want to understand those connections more clearly: who needs which information, when it is needed, and how an unclear process can create avoidable friction.','My school volunteering provides a practical point of connection. Event coordination, guest seating, setup, and backstage support involved contributing to a programme larger than any single task. That experience was not business employment, but it made the importance of organisation and clear responsibilities tangible.'),
  sec('Relevance to future study','My current interest in corporate law gives this introductory business learning another purpose. I want to understand a company as an organisation before trying to interpret the issues around it. A business has objectives, customers, internal processes, and constraints; learning to ask about those elements is part of building commercial awareness.','The next step is further reading and appropriate practical exposure. The provider’s diploma title is preserved as the title of the completed short course. It is not described as a university degree, and it does not establish professional legal or management qualifications.')]),
 ('business-finance','Introduction to Business Finance','Alison','October 2025','Business','https://alison.com/verify/640283d4a4','3998-36834668',[
  sec('An introduction to the financial perspective','My profile records Introduction to Business Finance, issued by Alison in October 2025, with credential ID 3998-36834668. The honours entry describes study of the history, principles, and investment analysis tools of business finance. The course is included once in this learning record, even though it appears in two profile sections.','Finance is relevant to my interest in corporate law because I want to understand the commercial setting around a decision. A transaction is more meaningful to study when its purpose and financial assumptions are considered alongside the formal steps. This course is introductory context, not evidence of professional financial analysis.'),
  sec('Questions beyond a headline','When reading about a company or investment, I want to ask what the business is trying to achieve and which assumptions support the decision. What is expected to create value? Which uncertainties might change the outcome? What information would a reader need before reaching a stronger conclusion?','Those questions are particularly relevant to my interests in mergers and acquisitions and private equity. They are areas I hope to study in more depth. I have not worked on transactions or advised investors, and the portfolio does not treat a short finance course as equivalent to that experience.'),
  sec('Building a useful foundation','My business administration course offers an organisational perspective; this course adds a financial one. The two can help me read a commercial development with more structure. My task is to become clearer about what I understand, what I can support with a source, and what needs further explanation.','A practical next step would be to follow one public business development over time and separate its stated objectives, available information, and unanswered questions. That exercise would help turn introductory learning into better research habits without presenting it as investment advice or a professional valuation.')]),
 ('aircraft-design','Introduction to Aircraft Design','Alison','May 2025','Aviation','https://alison.com/verify/f1e8c7db59','3071-36834668',[
  sec('A design perspective on aviation','My profile records Introduction to Aircraft Design, issued by Alison in May 2025, with credential ID 3071-36834668. The honours section uses a slightly different title, Introduction to Aviation Design, and refers to aircraft design procedures and technology. This page follows the title in the certification record and treats the entries as the same learning activity.','The course belongs to an earlier chapter when aviation was my intended career direction. It gave a structured place to explore a subject that had interested me beyond the classroom. It is recorded as introductory online learning, not an engineering degree or aircraft design qualification.'),
  sec('Looking at a system as a whole','Design invites questions about how individual choices affect the whole. Rather than treating an aircraft as one object, I want to understand how different components, requirements, and constraints are considered together. That wider way of looking at a problem is one reason aviation held my attention.','The relevance to my present direction is the habit of examining connections. An organisation, a product, or a transaction also needs to be understood in context. That does not make the subjects interchangeable, but it explains why the earlier course remains part of my learning story.'),
  sec('Keeping the learning in perspective','A short course can introduce terminology and a framework for further questions. It cannot, by itself, demonstrate the ability to undertake specialist engineering work. My role here is that of a student learning about a subject, and the wording of this page keeps that boundary visible.','A useful next step is to explain one design question in plain language and identify the information needed to answer it. For me, that is part of learning to communicate technical curiosity more carefully. The source link allows readers to inspect the credential rather than rely only on the portfolio description.')]),
 ('aviation-management','Basics of Aviation Management','Alison','March 2024','Aviation','https://alison.com/verify/cc4ec37d25','6052-36834668',[
  sec('The wider operation around a flight','My profile records Basics of Aviation Management, issued by Alison in March 2024, with credential ID 6052-36834668. Its honours description refers to flight operations, airport security, and risks. It is one of the early structured learning activities connected to my interest in aviation.','My later Global Airports Forum reflection gives context to that interest. I wrote about how a short boarding delay can connect to gate availability, crew duty limits, aircraft rotations, baggage, and coordination. The course and the event represent different types of learning, but both drew my attention to the wider operation.'),
  sec('Coordination as a recurring theme','The question that interests me is how many individual decisions contribute to a result that feels straightforward to the person using it. A passenger may notice whether a journey runs smoothly; understanding the operation requires looking at the work behind that experience.','That theme also connects to my practical school volunteering. A graduation programme depends on setup, seating, logistics, staff support, and backstage activity. The settings are very different, but both encourage attention to responsibilities and the flow of information between people.'),
  sec('An earlier interest, still part of the record','My current career direction is corporate and commercial law. This aviation course remains in the portfolio because it documents how my interest in organisations and systems developed. It is not presented as current aviation employment or a professional licence.','The next useful step is to revisit the operational questions through a broader commercial perspective: what an organisation needs to deliver its service, how it plans, and how decisions affect the wider system. Further study and practical experience would be needed before drawing specialist conclusions about aviation operations.')]),
 ('crew-management','Crew Management on Multi-Pilot Aircraft','Alison','January 2024','Aviation','https://alison.com/certification/check/2y10MjgCMik9bOBpRxHAjte8mp7VozAs2192PrAxkYWLGKyTYqa62','AC-5337-36834668',[
  sec('An early structured step','My profile records Crew Management on Multi-Pilot Aircraft, issued by Alison in January 2024, with credential ID AC-5337-36834668. Crew Management in Multi-Pilot Aircraft is the associated skill. An early LinkedIn post also records completing the course, making it one of the clearest starting points in my independent learning record.','The title centres on an environment where people must work together towards a shared outcome. That perspective appealed to my interest in aviation and in the standards behind an operation that can look effortless from the outside. The course is online learning; it does not establish flight training or operational crew experience.'),
  sec('Communication and shared understanding','One useful question to carry from crew management learning is how people build a shared understanding of a situation. Who has the relevant information? How is uncertainty communicated? What happens when an assumption is left unstated? Those questions make communication more than simply passing on a message.','They also provide a point of connection to my school volunteering and my wider learning about organisations. When several people contribute to a programme, clarity about an immediate task can affect the wider result. That connection is a learning perspective, not a claim that the responsibilities in those settings are equivalent.'),
  sec('What the course does and does not show','This credential records a completed course in the provider’s format. It does not mean I am a pilot, a qualified crew member, or an instructor. My present direction is corporate law, and the course remains as evidence of the earlier interests that helped shape my attention to coordination.','A useful next step is to examine a practical teamwork experience and describe what information helped the task succeed. That turns a broad interest in communication into something observable. It also keeps the learning record connected to actual examples rather than leaving a skill label without context.')])
 ]
 for name,title,provider,date,tag,url,credential,sections in courses:
  sections.append(sec('Credential and source','The issue date, provider, and credential link on this page are taken from my LinkedIn record reviewed on 6 October 2026. The link opens the provider record shown on that profile. It has not been independently audited by this website. This entry records completed learning; it does not imply a separate professional authorisation.'))
  add('learning/'+name+'.html',title,'Learning',title+' — completed with '+provider+' in '+date+'. The credential, learning context, and connection to my current direction.',sections,date=date,label=provider+' · '+date,tags=tag.lower(),source=url,source_label='Open credential record',facts=[('Provider',provider),('Listed issue date',date),('Evidence type','Course completion'),('Credential ID',credential or 'Provider-linked certificate')],related=['learning.html','skills/business.html' if tag=='Business' else 'skills/systems.html','direction.html'])

 add('skills/business.html','Understanding the business first.','Skills','Administration, finance, sales, entrepreneurship, and resilience as an introductory commercial foundation.',[
  sec('The evidence behind the theme','My business learning includes Diploma in Business Administration and Introduction to Business Finance from Alison, and Sales Fundamentals for Entrepreneurs and Resilience: Thriving as an Entrepreneur from LinkedIn Learning. Business Administration, Sales Operations, Entrepreneurship, and Business Resilience appear in my profile’s five-skill list.','These entries represent structured learning across related subjects. They are presented as foundations rather than professional competence. I have not described myself as a financial adviser, a business owner, or a commercial consultant.'),
  sec('Different views of one organisation','Administration asks how the work is organised. Finance adds questions about objectives, information, and the assumptions around a commercial decision. Sales adds the customer perspective: who the business serves and how it communicates value. Resilience focuses attention on responding when a plan does not unfold as expected.','I want to become better at connecting those perspectives when I read about a company. A headline rarely tells the entire story. Understanding what a business is trying to do, what it depends on, and which uncertainties remain is a more useful starting point for analysis.'),
  sec('Connection to corporate law','My current ambition is corporate and commercial law, especially mergers and acquisitions and private equity. Business learning gives me introductory context for that ambition. It helps identify what I need to investigate further, rather than allowing me to skip the more demanding study ahead.','The direction pages collect those questions. They focus on how a decision is understood, what information is needed, and how a student can build commercial awareness responsibly. They do not present legal conclusions or experience of advising clients.'),
  sec('The next evidence to build','A practical next step is a sourced commercial reading note. It could identify a company’s stated objective, summarise available information, and separate the open questions from conclusions that the evidence supports. That would provide something a reader could assess directly.','Until that work exists, this capability page remains attached to the courses that support it. The goal is to add substance through learning and experience, not to turn introductory course labels into a stronger claim than they justify.')
 ],related=['learning/business-administration.html','learning/business-finance.html','direction/transactions.html'])
 add('skills/communication.html','Clarity is a form of responsibility.','Skills','Communication through volunteering, multilingual development, and public reflection.',[
  sec('A practical example','At the AIS graduation ceremony in May 2025, I helped with event coordination, guest seating, logistics, setup, attendee guidance, and backstage operations. The role is recorded as Student Volunteer on my LinkedIn profile. Those duties involved supporting staff and students as part of a wider programme.','The usefulness of communication in that setting is concrete. An attendee needs the right guidance, a task needs to be understood, and staff need support that fits the flow of the event. I do not enlarge that role into overall event leadership, but it gives a practical example of contribution.'),
  sec('Writing as evidence','My LinkedIn posts describe experiences at aviation, cybersecurity, technology, finance, real estate, and governance events. They offer a reader the opportunity to inspect how I select an observation and explain why it mattered to me.','Writing is also a skill I want to improve. A strong reflection should distinguish what I saw from what I inferred, use an appropriate source where one is needed, and make a point without relying on excitement alone. The journal preserves source links so that readers can compare the expanded narrative with its original context.'),
  sec('Language and listening','My profile lists eight languages at different levels. Urdu and Punjabi are native or bilingual; Hindi is full professional; English is professional working; Arabic is limited working; French, German, and Korean are elementary. Those differences are relevant to communication and should remain visible.','After the UNESCO forum I wrote about the value of conversations with people from different countries and backgrounds. Listening to different perspectives can reveal how much context sits behind a position. I want to develop that attention alongside my ability to express my own ideas.'),
  sec('A continuing development priority','Clear communication is one of the foundations I want to carry into future legal study. That means developing accuracy, structure, and an awareness of the reader, rather than simply sounding formal. My current evidence is student-level volunteering and writing.','The next step is more practice in real tasks: explaining a difficult idea, writing a sourced summary, asking a focused question, and checking that another person has understood. Those examples would offer stronger evidence than an unsupported claim of advanced communication skills.')
 ],related=['experience/graduation.html','languages.html','journal.html'])
 add('skills/systems.html','Looking behind the visible result.','Skills','An interest in systems shaped by Computer Science, aviation learning, and technology events.',[
  sec('Where the interest comes from','I study Computer Science alongside Mathematics and Physics at International A Level. Outside school, aviation courses and events helped me become interested in how separate components, people, and decisions contribute to one outcome. My later technology reflections extend that interest into AI, cybersecurity, identity, and business.','This page describes a way of approaching learning, rather than a formally assessed skill on my LinkedIn profile. Systems thinking is the connection between these experiences: looking at the wider context instead of treating an impressive result as self-explanatory.'),
  sec('The airport example','In my Global Airports Forum post, I described how a short boarding delay can connect to gate availability, crew duty time, aircraft rotations, baggage, and wider coordination. The observation changed how I looked at something that can appear simple from the passenger’s perspective.','The useful habit is to ask what dependencies sit behind an outcome. Which teams need to coordinate? Which information arrives at the right time? What happens when one assumption changes? These questions encourage a more careful account of a system without pretending to have operational expertise.'),
  sec('The technology example','At Money20/20, I wrote about AI agents and questions of identity and authorisation. At the UNESCO forum, I focused on responsibility and governance. Those experiences shifted my attention from what technology can demonstrate to what organisations need before they can rely on it.','That distinction is relevant to my current commercial interests. A business adopting a new tool has more to consider than a feature list. I want to understand the human, organisational, and technical context around the decision, while recognising that specialist conclusions require deeper knowledge.'),
  sec('Applying the habit carefully','This portfolio itself applies a small version of that approach. Content, evidence, navigation, reading modes, and accessibility need to support one another. A feature that looks attractive but hides useful information would work against the site’s purpose.','My next development step is to make those connections clearer in research and writing. I want to identify assumptions, describe dependencies, and keep the limits of my understanding visible. The result should be a better question and a more useful explanation, not an inflated technical title.')
 ],related=['events/airports.html','events/money2020.html','projects/portfolio.html'])

 language_groups=[
 ('established','Languages rooted in my background.','Urdu, Punjabi, and Hindi, with the individual proficiency levels recorded on my profile.',[
  sec('The stated levels','My LinkedIn language record lists Urdu and Punjabi at native or bilingual proficiency, and Hindi at full professional proficiency. These are the labels recorded on the profile reviewed on 6 October 2026. The portfolio retains each label rather than grouping all three under one uniform claim.','A language profile is most useful when it gives an accurate starting point for a conversation. These entries form the established-language group in my record. They are separate from the working and elementary languages described on the other pages.'),
  sec('A background with more than one language','As a Pakistani student living in Saudi Arabia, my wider profile combines different linguistic and educational contexts. This language record is one part of that background. It sits alongside my English-medium public writing and my current International A Level studies.','Speaking more than one language can make differences in phrasing and perspective more noticeable. My aim is to communicate with attention to the setting and the person reading or listening, rather than assume that the same wording works equally well in every context.'),
  sec('Proficiency and specialist work','The labels here are self-reported profile levels. They are not presented as qualifications in translation or interpretation. A specialist task, including legal or technical communication, can require vocabulary, methods, and professional standards beyond a general language label.','I do not claim to provide professional translation or legal interpretation in these languages. For a practical conversation, the subject, format, and level of detail still matter. Keeping that distinction clear makes the profile more useful than relying on a language count alone.'),
  sec('Keeping the record useful','The language hub provides the complete table, including the lower proficiency levels for other languages. This allows a reader to see the whole record without assuming equal ability across it.','Future evidence could add more context through demonstrated writing, an identified assessment, or actual tasks. Until then, the portfolio presents the profile labels faithfully and avoids assigning invented scores or credentials. The purpose is clarity about the current record and room for it to develop.')]),
 ('working','Communication across my current setting.','English at professional working proficiency; Arabic at limited working proficiency.',[
  sec('Two languages, different stages','My LinkedIn profile lists English at professional working proficiency and Arabic at limited working proficiency. It also includes a Duolingo score of 130 under English, dated December 2025. This page preserves the proficiency labels and treats the score as a profile-reported note.','The available record does not identify that score as a formal English test result. This portfolio therefore does not convert it into an admission qualification, a certified assessment, or a CEFR level. A reader should use the stated proficiency and actual communication examples as the available context.'),
  sec('English in academic and public writing','My current education and public LinkedIn posts provide a practical setting for English. The journal contains edited reflections based on those posts, with source links that allow the writing to be assessed in context.','My development goal is more precise expression: structuring an argument, selecting evidence, and making a complex subject easier to follow. Those goals matter to my future interest in law, where I want to become better at careful reading and clear explanation. They remain development goals at my present student stage.'),
  sec('Arabic in the place I live','Arabic is relevant to living in Riyadh, but my listed level is limited working proficiency. That is a materially different claim from fluent or professional specialist ability. The distinction remains visible in the main language table.','I want the portfolio to represent language development honestly. A reader should not have to infer the level from a decorative symbol or a percentage. The label is the strongest available summary, and the context of a particular task would still need to be considered.'),
  sec('The next evidence to add','A useful language record develops through practice and specific examples. Clear writing, successful conversations, and identified assessments can add context that a broad label does not provide.','For now, English and Arabic are presented at their recorded levels, without a claim of legal interpretation or translation competence. The established-language and early-learning pages complete the picture and make it clear that the eight-language record contains several different stages of ability.')]),
 ('exploring','At the beginning of three languages.','French, German, and Korean are listed at elementary proficiency.',[
  sec('Learning, rather than fluency','My profile lists French, German, and Korean at elementary proficiency. These entries belong to the early-learning group in my language record. They are not presented as languages in which I can carry out unrestricted professional work.','That distinction is intentional. A language can be a meaningful interest without being a completed achievement. Including the elementary level makes the record more accurate and gives future development a clear starting point.'),
  sec('The German score note','The German entry includes a Duolingo score of 10, dated April 2025. It is reproduced as a profile-reported note. The available text does not establish a formal language examination or a certified proficiency level.','I do not translate that score into a CEFR category or imply that it qualifies me for study or work in German. The elementary proficiency label is the clearest statement in the record, and it remains the basis of this page.'),
  sec('Why early learning belongs here','This portfolio is intended to show development as well as completed learning. The elementary languages fit that purpose when their limits are clear. They show areas of exploration alongside the languages recorded at stronger levels.','The useful question is what evidence could make the next update more informative. A specific reading, writing, listening, or speaking task would add more context than a simple increase in a decorative progress bar. Different abilities can develop at different rates, so an invented percentage would obscure rather than clarify.'),
  sec('A practical development perspective','My broader communication goal is to become more attentive to wording and context. Early language learning can support that curiosity, but it should not be used to claim specialist communication skills that have not been demonstrated.','The complete table on the language hub shows all eight languages and their stated levels. This page gives the elementary group its proper place in that record: an interest in progress, with no claim of fluency, professional translation, or legal interpretation. Future updates should be supported by actual practice or an identified assessment.')])]
 for name,title,desc,sections in language_groups:
  add('languages/'+name+'.html',title,'Languages',desc,sections,source=PROFILE+'details/languages/',source_label='View listed language levels',related=['languages.html','skills/communication.html','about.html'])

 add('direction/transactions.html','Interested in the decision behind the deal.','Direction','The questions drawing me towards mergers, acquisitions, and private equity.',[
  sec('An area I want to understand','Mergers and acquisitions and private equity are specific interests in my LinkedIn biography. They sit within a broader ambition to pursue corporate and commercial law. I am interested in how a business decision is understood from several perspectives and how the people involved work through uncertainty.','At this stage, that is an area of intended learning. I have not worked on a transaction, advised a client, or completed a law degree. This page is a record of questions shaping my direction, rather than a transaction portfolio.'),
  sec('Beginning with the commercial purpose','The first question I want to investigate is what a business hopes to achieve. Why pursue a transaction? What would success look like? Which assumptions does the decision depend on? Looking at the stated purpose gives a student a more useful starting point than trying to memorise a deal headline.','My introductory finance and administration courses provide context for those questions. They encourage me to look at the organisation and the commercial setting. They do not supply the full legal, financial, or practical knowledge required to assess a real transaction.'),
  sec('Information, uncertainty, and responsibility','Another area I want to understand is how decision-makers establish what they need to know. Which information would change their view? Where is uncertainty accepted, reduced, or left open? Who needs to understand the consequences before the next step is taken?','These questions connect to themes in my other learning. Aviation introduced coordination; technology events introduced implementation and accountability. The subjects differ, but each encourages attention to the system around an outcome rather than only the visible result.'),
  sec('A realistic development plan','My present priorities are academic progress and more careful commercial reading. A useful next exercise would be to follow a public transaction announcement and summarise its stated objectives, the available information, and the questions I cannot answer from that record.','That would be a student research exercise, with sources and limits made explicit. Further legal study and supervised experience would be needed before the questions could become professional judgement. I want to earn that progression through work rather than suggest that the ambition itself establishes competence.')
 ],related=['learning/business-finance.html','skills/business.html','direction.html'])
 add('direction/technology.html','Technology creates responsibilities.','Direction','AI governance, identity, and cybersecurity as questions for a developing commercial perspective.',[
  sec('A different view of innovation','My interest in technology has grown through Computer Science study and events in Riyadh. LEAP made emerging products tangible. Black Hat MEA introduced another view through cybersecurity. Money20/20 drew my attention to identity and authorisation, while the UNESCO forum shifted the conversation towards accountability and governance.','The connection to my current legal ambition is the set of questions these experiences create. I want to understand how a business can use a technology and what responsibilities follow from relying on it. These are student learning questions, not legal opinions.'),
  sec('Capability is only the first question','A demonstration can show that a system performs a task. My Money20/20 reflection asks what is needed before organisations can rely on that capability in use. Identity, security, reliability, and infrastructure were the themes that stood out to me.','AI agents made the question particularly concrete: if a system takes an action for a person, how is authorisation established and how much control remains with that person? I want to examine such questions carefully without assuming that a conference discussion settles the answer.'),
  sec('Responsibility and perspective','At the UNESCO forum, I wrote about who is responsible when AI causes harm, how human accountability is maintained, and how different countries approach governance. Conversations with people from different backgrounds added to that perspective.','The experience made me interested in implementation as well as principles. How is a broad goal translated into an actual process? Who needs to understand it? What information would show that the process is working? Those questions connect technology to the wider organisation around it.'),
  sec('Where I want to take this interest','My next step is stronger research and clearer writing. I want to distinguish product claims from demonstrated use, a policy ambition from its implementation, and my own interpretation from a sourced fact. The journal is a place to practise that distinction.','This interest does not establish cybersecurity qualifications or professional AI governance expertise. It provides a direction for learning and a point of connection to corporate law. Further study and practical experience should make the questions more precise and the record more substantive.')
 ],related=['events/unesco.html','events/money2020.html','journal/ai-governance.html'])
