def populate_experiences(add,sec,PROFILE):
 def post(id):return 'https://www.linkedin.com/feed/update/urn:li:activity:'+id+'/'
 events=[
 ('unesco','When the conversation became about responsibility.','UNESCO Global Forum on the Ethics of AI','September 2026','governance,technology','7505991669549256705',[
  sec('What I expected, and what changed','I attended the fourth UNESCO Global Forum on the Ethics of AI in Riyadh. My reflection begins with an expectation: I thought it would be closer to a large technology exhibition, with products, companies, and new capabilities on display. The experience was different. The conversations centred on what people and institutions are going to do with those capabilities.','I found myself listening to governments, researchers, international organisations, and people working on governance. The shift mattered because it moved the subject from technical possibility to responsibility. A system doing something impressive is only the beginning of a much wider set of questions.'),
  sec('The questions that stayed','In my post, I asked who is responsible when AI causes harm, how humans remain accountable when decisions involve machines, and how governments approach systems that operate across borders. I also noticed the discussion of environmental and energy demands.','The value of the event was not that it supplied one final answer. It showed me how many perspectives are involved and how implementation becomes part of the discussion. I left with a more concrete interest in the relationship between innovation, institutions, and the rules around them.'),
  sec('Learning through conversations','Some of the moments I valued most were conversations with people from different countries and backgrounds. I wrote that these exchanges made it clearer that there is no single universal perspective on AI: different settings bring different opportunities, risks, and priorities.','That was a useful reminder to listen before simplifying a subject. A policy discussion or business decision can look different when the assumptions and conditions behind it change. I want to carry that attention into my own reading and writing.'),
  sec('Connection to my current direction','My interest in corporate law gave the forum another relevance. I found myself thinking about how a business adopts AI, what information it relies on, and how people remain responsible for decisions. Those are questions I want to study further, especially the practical work needed to turn a principle into something people can use.','The related journal essay develops the central question: what comes after a technology becomes capable of performing a task? The original post remains linked so readers can see the experience that prompted the reflection.')], 'unesco.jpg'),
 ('money2020','Identity behind the transaction.','Money20/20 Middle East','September 2026','technology,business','7505617162829545472',[
  sec('More technology than I expected','I attended Money20/20 Middle East in Riyadh, initially expecting a finance-heavy event focused on banking and payments. In my post, I described finding a much wider technology conversation: AI, agentic AI, cybersecurity, digital identity, authentication, and the infrastructure around them.','That changed what I paid attention to. The subject was not simply what a technology could demonstrate, but what companies were building in order to use it. The exhibition brought several connected industries into one view and made their overlap easier to recognise.'),
  sec('The agentic commerce question','One session that interested me concerned AI agents taking actions for people. My reflection asked how a company would know that an agent was authorised to make a purchase or carry out a transaction, how identity would be established, and how much control a person should retain.','Those questions made an abstract development concrete. The ability to perform an action is different from knowing that the action is appropriate and authorised. I want to investigate that distinction further as part of learning about business, technology, and responsibility.'),
  sec('From pilots to products','Another discussion concerned moving AI from pilots into actual products. In my post, I connected this to data, security, reliability, and infrastructure. The point that stayed with me was the gap between demonstrating a capability and relying on it in a real operating environment.','This also connected to the other events I had attended. LEAP offered a broad view of innovation; Black Hat MEA provided cybersecurity exposure. Money20/20 showed another part of the same ecosystem, through financial services and the systems that make transactions possible.'),
  sec('A developing commercial lens','I left thinking more about AI, security, and identity than I had expected. For my current interest in corporate law, the experience offers questions worth pursuing about how organisations make technology useful and how responsibilities are understood.','The authorisation question is what I wanted to keep thinking about afterwards. If an AI agent acts for someone, what permission is needed, what can the person review, and how does anyone understand what happened? I have given that thought more space in the journal, because it connects a new technology to an ordinary decision.')], 'money2020.jpg'),
 ('leap','Seeing an idea move towards everyday life.','LEAP Riyadh','2026','technology','7501288436100923392',[
  sec('An exhibition that widened the view','I attended LEAP in Riyadh in 2026. I described seeing technologies associated with AI, autonomous transport, robotics, delivery systems, and new ways of interacting with services. The experience made developments I had followed more tangible.','I left excited by the possibilities I had seen. At the same time, I became more curious about what happens after a demonstration: who would use the product, which conditions it needs, and how it fits an ordinary day. Seeing an idea work made me want to understand the work around it.'),
  sec('The difference between seeing and understanding','The useful next question is what it takes for a demonstration to become a service people can depend on. A product needs more than an impressive moment on a stand. I want to understand the surrounding organisation, the intended user, the practical constraints, and the evidence behind a claim.','That perspective helps me revisit the event more carefully. Instead of treating every possibility as inevitable, I can ask which assumptions support it and what information would be needed to assess progress. This is part of developing better commercial and technical reading habits.'),
  sec('A personal part of the day','I also tried an F1 simulator and learned more about the Saudi Arabian Grand Prix. That brought a different kind of interest into the day, alongside the technology exhibits. I enjoyed the breadth of the event: it was possible to move from a discussion about emerging products to an experience that made another subject feel more tangible.','The wider impression was of ideas moving closer to practical use. My later Money20/20 and UNESCO reflections added another layer by focusing on identity, implementation, governance, and accountability around those capabilities.'),
  sec('What I want to carry forward','LEAP made technology feel closer and gave me more questions to carry away. I now find those questions useful in thinking about business too. An innovation has a purpose, a user, and an organisation around it, and I want to understand those connections instead of stopping at the impressive first moment.','The related journal page explores the gap between a demonstration and dependable use. It keeps a student’s curiosity visible while avoiding unsupported predictions about when a technology will replace an existing service or become part of everyday life.')],None),
 ('airports','The coordination you do not see.','Global Airports Forum','2025','aviation,business','7406670810586828802',[
  sec('A different understanding of airports','I attended the Global Airports Forum in Riyadh and wrote that it changed how I looked at airports. From the outside, terminals, runways, and aircraft movements can seem calm and routine. The discussions drew my attention to the decisions and dependencies behind that appearance.','My post used a small boarding delay as an example. What looks minor to a passenger can connect to gate availability, crew duty time, aircraft rotations, baggage sequencing, and wider coordination. I was interested in how one change can affect several parts of the operation.'),
  sec('Learning from people in the industry','I met aviation professionals and executives including Omar al Hosari, David Buczek, and Julius Norkunas. Hearing their perspectives on airport operations and strategy was one of the parts I valued most. It gave me a chance to listen to people working in a field I was trying to understand.',"Those conversations added something an exhibition alone could not. I was interested in the experience behind a person's view: what they notice, which problems they consider important, and how they think about the wider operation. I wanted to listen before assuming that the parts visible to a passenger explain how an airport works."),
  sec('Technology within the operation','I also wrote about the role of AI in airport management and the different ways technology was being discussed. The broader observation was how many systems, teams, and decisions need to work together for the passenger journey to feel straightforward.','That interest in invisible coordination remains relevant even though my career direction has changed. I want to understand what an organisation depends on to deliver its service, and how a result that looks simple can rest on a complex system.'),
  sec('An early interest that still matters','At the time, I hoped to pursue aviation. My intended career has since moved towards corporate and commercial law, but the experience still matters to me. It helped me become curious about organisations and dependencies, and about the preparation behind something that can seem simple when it is going well.','The forum connected my aviation courses to an industry setting. Crew management and aviation management had introduced related questions; the event made me think about how they appear in a much larger operation. I still return to the same idea: what needs to work together for someone using a service to have a smooth experience?')],None),
 ('blackhat','A closer look at digital trust.','Black Hat Middle East & Africa','2025','technology','7402361128523280384',[
  sec('Encountering the security perspective','I attended Black Hat MEA 2025. I described sessions and discussions about emerging threats, defence strategies, and the direction of technology in the Middle East. The event added a security perspective to interests I had previously explored through aviation and technology.','That wider exposure matters because a digital service is not only defined by what its interface allows a user to do. I want to understand the systems and decisions that support trust in its use. The event gave me another set of questions to pursue.'),
  sec('Learning at Black Hat','At Black Hat MEA, I completed ten hours of CPD activities and received a certificate carrying ten CPD credits, which I shared in my event reflection. It was an opportunity to learn about security in a setting with people discussing current threats, defence, and the technology around them.','I took part as a student learning about the field. What interested me was the work behind digital trust: the decisions, systems, and information that make a service dependable. I want to build on that introduction with more focused reading, especially where security connects to identity and the way a business uses technology.'),
  sec('Connections to later experiences','Cybersecurity themes appeared again in my Money20/20 reflection, alongside identity, authentication, and infrastructure. Seeing those topics in different settings made it easier to recognise how they connect to the way organisations use technology.','My current corporate-law ambition gives that connection another relevance. I want to understand how a business thinks about a system it depends on and the responsibilities around it. Further study would be needed before those questions could support specialist conclusions.'),
  sec('What I want to learn next','Black Hat widened my view of technology by putting security at the centre of the conversation. It made me more interested in the parts of a digital service that are easy to overlook when the interface works well. That is a perspective I carried into later events about identity, finance, and AI.','I would like to pick one security or identity question and read about it more carefully. What is the problem? Which assumptions matter? How would I explain it to someone new to the topic? A focused task like that would help me turn the first exposure into a clearer understanding.')],None),
 ('real-estate','Cities need people to become places.','Real Estate Future Forum','2026','business','7422345465716703233',[
  sec('A human perspective on development','I attended day three of the Real Estate Future Forum in Riyadh in 2026. The discussion moved beyond buildings and skylines towards how people live in cities, how communities form, and how a place gains meaning. I left thinking more about the human purpose of development than the visible scale of a project.','The themes I noticed included sustainability, density, lifestyle, and human-centred planning. What stayed with me was the idea that a physical development needs a social purpose. The experience broadened the way I thought about business and investment.'),
  sec('Ideas from the discussions','In my reflection, I referred to a point made by Peter Jonathan Jameson about the importance of people, proximity, and interaction. I also described Sir Richard Branson’s emphasis on culture, experience, and the people within a business.','Hearing those ideas as an attendee made me reconsider the most obvious way to look at a development. A physical asset is easier to describe than the life around it. I wanted to ask whose needs give the project its purpose and what the place makes possible for them.'),
  sec('Connecting commercial and human value','For my current interests, the forum offers a reminder to ask who a project is intended to serve. Investment and development can be discussed through numbers and physical outputs, but the experience of people is another part of the picture I want to understand.','That became a question I wanted to follow into my writing. How do the commercial aims of a development connect to the people who use it? What would make the project valuable in everyday life? The journal essay gives that thought more room, because it has relevance well beyond a single event.'),
  sec('A wider learning context','This event sits alongside finance, technology, and governance experiences in my portfolio. Together, they encourage me to look beyond the most visible element of a subject and consider the wider organisation and purpose around it.','I want to carry that human perspective into future reading about businesses and investment. A proposal has numbers and physical outputs, but it also has an intended purpose. Asking who benefits, and how, helps me understand the story behind a project rather than treating the visible result as the whole explanation.')],None),
 ('sand-and-fun','The discipline behind the display.','Sand & Fun Aviation Show','2025','aviation','7399801706664062976',[
  sec('An aviation experience with several dimensions','I attended the Sand & Fun Aviation Show in Riyadh during the period when aviation was my intended career direction. There were aircraft, displays, different aviation disciplines, and opportunities to hear from people in the industry. I enjoyed the spectacle, but the discipline behind it was what stayed with me.','The event was memorable for its visible performances, but the idea that stayed with me was the discipline behind them. A display can make precision look effortless. My reflection focused on the standards, technical skill, and dedication that such performances suggested.'),
  sec('The moments that stayed','I wrote about watching Luke Czepiela land on a moving truck, aerobatic displays from several countries, a paramotor team, Royal Saudi Air Force performances, and the night programme. These are observations from my attendance, not activities in which I participated as an operator.','Watching a display made me think about the preparation I could not see. What had to happen before that moment? Which standards shaped the performance, and how did people coordinate? I was there as a spectator, and the experience made me more curious about the work behind the precision.'),
  sec('An earlier direction, a lasting question','At the time, aviation was my long-term career goal. My current direction is corporate law. The earlier experience remains useful as part of understanding how I became interested in complex systems and the people responsible for their performance.','The lasting question is what sits behind the result. What preparation makes the visible outcome possible? What standards govern the work? How do teams coordinate? Those questions connect to the broader pattern in my learning, even as the intended profession changes.'),
  sec('What I took away','Sand & Fun brought another dimension to the crew management, aviation management, and aircraft design courses I had taken. A course gave me an introduction; the show made me think about the people applying skill and discipline in an actual setting. I enjoyed having both kinds of experience around the same interest.','My original reflection still comes from that earlier interest in aviation. I like being able to look back at it now and see what has stayed with me. The intended career may have changed, but the curiosity about preparation, standards, and people working together continues to connect my interests.')],None),
 ('electric-mobility','A new view of how people move.','Riyadh EV Auto Show','2025','technology,business','7409623371191271424',[
  sec('The experience preserved in my annual reflection','My 2025 annual reflection mentions experiencing electric buses at the Riyadh EV Auto Show. The annual reflection places this alongside aviation events and cybersecurity learning as an example of exploring how technology is reshaping different industries.','I mentioned the visit in my annual reflection, alongside aviation events and cybersecurity learning. The electric buses were the part I chose to remember. It was a brief experience, but it added another angle to my interest in transport and in how technology changes the way people use a service.'),
  sec('Mobility as a wider interest','Transport connects several of my interests. Aviation first made me think about operations and coordination. Electric mobility adds a different question: how does a product change the experience of getting from one place to another? I am interested in the technology, but also in the people it is intended to serve.','I want to understand the organisation around a mobility product as well as the product itself. Who is it intended to serve? Which conditions need to be in place for it to be useful? What evidence would show that the proposed benefits are being realised? Those are questions for further study.'),
  sec('From product interest to commercial questions',"My later interest in CEER brought me back to practical design and the local setting around a product. I like asking how an innovation addresses an actual need, instead of simply noticing that it is new. The intended user's experience is a useful place to begin that question.",'My interest in corporate law makes the commercial side of mobility more engaging too. A product sits within an organisation and a market, with decisions about who it serves and what makes it useful. My business courses give me a starting point for asking about that wider setting and the purpose behind a launch.'),
  sec('A question to carry forward','The visit was one small part of a year spent exploring different industries in Riyadh. I wanted to keep the electric-bus experience alongside the other things that caught my attention. Together, they show why I became more interested in the organisations around a product and the people who depend on it.','I would like to learn more about the business questions around mobility: what makes a service useful, how a company understands its users, and which conditions help a new product fit everyday life. Those questions connect the visit to my wider learning, while leaving plenty for me to investigate next.')],None),
 ('global-ai','An announced intention to explore AI.','Global AI Show Riyadh','2026 · announced participation','technology','7465766602609758208',[
  sec('Why the event interested me','I announced plans to attend Global AI Show Riyadh on 29–30 June 2026. I have not added a reflection about a completed visit, so this chapter focuses on what interested me about the subject. AI had already become a recurring theme in my learning through technology, finance, and governance events.','The appeal was the chance to explore a field that kept appearing in different conversations. I was curious about what organisations were building, how they expected people to use it, and which questions mattered after the first demonstration. Those interests remain worth following through the experiences I have written about elsewhere.'),
  sec('Why the subject fits my interests','AI appears across several of my more detailed event reflections. At LEAP I encountered demonstrations and products. At Money20/20 I wrote about agentic AI, identity, and infrastructure. At the UNESCO forum I focused on responsibility and governance.','My interest in the Global AI Show connects to that wider curiosity. LEAP showed me emerging products, Money20/20 brought identity and implementation into view, and the UNESCO forum focused on responsibility. I want to understand how those conversations fit together when an organisation decides to use AI.'),
  sec('Useful questions for future learning','For an AI event, I would want to ask what a system can demonstrate, what evidence supports its claims, and what is required before it can be used reliably. A commercial perspective also asks who needs the product and what problem it is intended to solve.','I would want to come away with a clearer example to think about, rather than only a broad impression. Understanding what a product is meant to do, and what it depends on, would give me a useful next step for reading. That is the kind of question I enjoy carrying from an event into my writing.'),
  sec('Where I want to take the interest','The event pages give me a way to keep different experiences connected without treating them as identical. Some began with a visit and a specific observation; this one began with a plan and a subject I wanted to explore. The completed visits offer a clearer place to follow the questions that actually stayed with me.','My announcement is linked below, and the related pages explore experiences I have reflected on in more detail. I would like a future visit to produce something concrete to think about: a question I had not considered, a clearer explanation, or a connection that makes the subject easier to understand.')],None),
 ('global-games','An interest in the technology of games.','Global Games Show Riyadh','2026 · announced participation','technology,business','7464961205401497602',[
  sec('An interest at the intersection of my subjects','I announced plans to attend Global Games Show Riyadh on 29–30 June 2026. I have not added an account of a completed visit. What drew me to the subject was its connection to Computer Science, technology, and business: a digital product needs both the system behind it and an experience people want to use.','I wanted to explore how those parts come together. What helps someone understand a product? Which design decisions make the first experience easier? How does the organisation think about its audience? Those questions interest me beyond games too, because they connect technical work to the purpose it is meant to serve.'),
  sec('Where the interest connects','My wider portfolio includes Computer Science study, technology events, and business learning. A games event sits at an intersection of those interests, where a digital product can be considered through both the technology behind it and the experience of the people using it.','The connection comes from my studies and broader curiosity, rather than a career in games. I am interested in the way a product works and the way someone experiences it. Looking at both together gives me another route into the commercial questions I have begun exploring through administration, finance, and sales learning.'),
  sec('Questions worth exploring','A useful learning question is how a product’s design serves its intended user. What makes the experience understandable? Which decisions help someone begin using it? What would need to work together for that experience to be reliable?','Business adds questions about audience and value. Who is the product for? What keeps someone interested? How does the organisation understand what people need? My courses give me a starting point for thinking about those questions, and I would like future learning to make the connection between design and commercial purpose more concrete.'),
  sec('Questions to carry forward','The announcement below is where I first shared the plan. Elsewhere, I have written in more detail about visits to technology and business events. I enjoy connecting those experiences because a question about reliability, user experience, or responsibility can travel across industries that initially seem quite different.','I would like future experiences in this area to give me a clearer example to think through: a design choice, a user problem, or an explanation of how an organisation builds a product. For now, this is an interest I want to explore alongside my current studies and developing commercial perspective.')],None)
 ]
 for name,title,event,date,tags,id,sections,image in events:
  kw={}
  if image:kw={'image':image,'image_alt':('Stage screen at the UNESCO Global Forum on the Ethics of AI in Riyadh'if image=='unesco.jpg'else 'Money20/20 Middle East event photograph from my original post'),'image_caption':'Photograph from my original event post.'}
  add('events/'+name+'.html',title,'Events',event+' · '+('Why I wanted to explore this event.'if 'announced'in date else 'What I experienced and the questions I took away.'),sections,date=date,label=event,tags=tags,source=post(id),source_label='Read my original post',source_note='My original reflection',source_description='I first shared my thoughts in the post linked below. Here, I have given the ideas more room and connected them to the questions I want to explore next.',evidence_type='Announcement'if 'announced'in date else 'Event reflection',related=['events.html','journal.html','skills/systems.html'],**kw)

 essays=[
 ('commercial-design','Innovation should remember the person.','technology,business','7507880159203504128',[
  sec('A detail that changed the emphasis','My post about CEER’s EXOBOT models focused on innovation designed around practical needs. I was interested in the relationship between advanced technology and the experience of the person using a product. The commercial question was not simply how much technology could be added, but which decisions made it useful.','That perspective connects to the events I have attended. A demonstration can make a new capability visible. Understanding a product requires asking what problem it is meant to solve and how the design fits the conditions in which someone will use it.'),
  sec('Keeping the user in the picture',"I wrote about cabin comfort in Saudi Arabia's climate and the value of keeping physical controls for essential functions. Those details caught my attention because they brought the conversation back to an ordinary person using the product. A small design choice can matter more when it affects something someone does repeatedly.",'I was responding to a product announcement, so what interested me was the reasoning behind the design. Which needs had the company chosen to focus on? How would the controls or cabin features fit an everyday experience? Those questions gave me more to think about than a list of performance figures.'),
  sec('A commercial perspective worth developing','A useful next question is how a company understands the needs of its intended audience. Which features answer an actual problem? What trade-offs are being made? What information would help a reader judge whether the proposed benefit has been demonstrated?','My sales, administration, and finance courses help me approach the commercial side of those questions. I want to understand the promised value, the intended user, and the organisation behind the product. Reading an announcement with those different angles in mind makes it easier to see what I understand and what I would want to know next.'),
  sec('The connection to my direction','My current interest in corporate law includes understanding businesses as organisations making decisions. A product announcement offers one small window into that work: an ambition, an intended customer, a practical setting, and assumptions about what will create value.','The thought I want to carry forward is to keep the person using a product in view. Innovation becomes more interesting when I understand its purpose, and design becomes more useful when it responds to that purpose. I want to bring that question into more of my commercial reading, not only automotive announcements.')]),
 ('ai-governance','The question after capability.','technology','7505991669549256705',[
  sec('What happens after it works?','I went to the UNESCO Global Forum on the Ethics of AI expecting to see more of what technology could do. Instead, I found myself thinking about what happens after a system becomes capable of doing something. That was the central shift in my original reflection.','A demonstration can create excitement, but capability does not finish the conversation. My questions became about responsibility, human accountability, the role of institutions, and how broad ideas are put into practice. The experience changed the lens through which I wanted to look at AI.'),
  sec('The setting changes the question','Conversations with people from different countries and backgrounds were among the parts I valued most. I wrote that they made it easier to see why there is no single universal perspective on AI. Different settings bring different priorities and different conditions.','That observation matters to how I want to learn. A simple description can leave out the assumptions that make a position understandable. Before deciding that one answer applies everywhere, I want to ask whose circumstances are being considered and what information is missing.'),
  sec('Principles need a practical route','My reflection also focused on implementation. It is one thing to express a broad goal; it is another to decide how an organisation will act on it. I want to understand the people, processes, and information needed to make that step useful.','These are questions that connect to my interest in corporate law. Businesses adopt technology within a wider setting of responsibilities and decisions. Understanding that setting requires more than following the most impressive feature of a new system.'),
  sec('A student’s next step','I would like to focus on one of those questions and read about it properly. Who is responsible for a decision, and how is that responsibility understood in practice? Working through a specific example would help me move beyond the broad language and explain the issue with more clarity.','The forum left me with a question that still feels useful: once a system can do something, what needs to happen before people can rely on it? I want to understand the human and organisational work around that transition. Capability gets attention first, but responsibility is part of what makes the technology matter.')]),
 ('agentic-commerce','An action needs more than an instruction.','technology,business','7505617162829545472',[
  sec('The question that made AI concrete','At Money20/20 Middle East, I was interested in discussions of agentic commerce: AI systems taking actions for people. My original post asked how a company knows an action is authorised, how identity is established, and how much control the person should have.','Those questions stayed because they connected technology to an ordinary action, such as making a purchase. Performing the task is not the whole problem. The surrounding system needs a way to understand the relationship between the person, the agent, and the action.'),
  sec('Beyond the impressive demonstration','The event also included a discussion of moving AI from pilots into actual products. I wrote about data, security, reliability, and infrastructure as part of that transition. The distinction between a demonstration and something an organisation relies on became more important to me.','I wanted to understand what changes between a successful demonstration and a dependable product. Which assumptions does the system rely on? What happens when the circumstances change? What would help someone understand the result? Those questions give me a clearer way to approach the subject instead of stopping at the impressive first moment.'),
  sec('Connected industries, connected questions','Walking through the exhibition brought AI, cybersecurity, identity, payments, banking, and infrastructure into one view. I connected the experience to LEAP and Black Hat MEA, which had shown different parts of the same wider technology landscape.','The commercial perspective I want to develop involves recognising those connections without flattening the differences between subjects. A company adopting a tool may depend on several systems around it, and each deserves more careful study than an event summary can provide.'),
  sec('What I want to investigate next','A useful next exercise would be to trace one proposed agent action and identify the open questions at each step. Who requests it? What permission is given? What can the person review? Which information would show what happened?','Tracing one action would make the question more concrete. I would want to follow the request, the permission, the action itself, and what the person can see afterwards. Money20/20 made that sequence interesting to me because it connects an emerging technology to familiar questions about control and trust.')]),
 ('human-cities','An asset becomes a place through people.','business','7422345465716703233',[
  sec('Looking beyond the skyline','At the Real Estate Future Forum, I noticed a discussion that moved beyond constructing buildings towards how people live, work, and connect. My original reflection focused on the human element of development and the experience that turns a physical asset into a meaningful place.','That idea resonated because it challenged the most visible way of looking at real estate. A skyline can be impressive, but the question I wanted to ask was what the development makes possible for the people who use it.'),
  sec('Value with a wider context','My post referred to ideas about density, proximity, interaction, culture, and experience. These are different perspectives, yet they all point towards the purpose surrounding the physical result. I want to understand how commercial objectives connect to that lived context.','I left with a question I had not given enough attention to before: whose needs make a development meaningful? That is a different way to look at an asset. It makes me think about the intended purpose, the people using the place, and what might matter to them after the opening announcement is over.'),
  sec('The connection to business','The same question can be useful when looking at a business. A product, service, or investment is part of a wider relationship with the people it is intended to serve. Understanding its stated purpose should include understanding that relationship.','Administration, finance, and sales give me different starting points for considering a business. One asks about the organisation, another about value and resources, and another about the customer. I want to bring those perspectives together when reading about development, while leaving room for the people whose experience gives the proposal its purpose.'),
  sec('A habit for future reading','When reading a development announcement, I want to separate the physical proposal, the commercial objective, and the claimed benefit to people. What information supports each part? Which assumptions remain open? What would show that the result serves its intended purpose?','The forum changed what I wanted to notice in future announcements. I still find a physical project interesting, but I want to ask what it enables for people and how its stated purpose connects to actual use. That question travels well beyond real estate into products, services, and the way businesses describe value.')]),
 ('innovation','The distance between a demo and daily life.','technology','7501288436100923392',[
  sec('The excitement of seeing something work','LEAP made technologies I had followed feel much closer. Seeing a demonstration in person can give an idea a different kind of excitement, because there is something tangible to look at and ask about. I enjoyed that feeling, and I wanted to understand more about what would make the idea useful outside the exhibition.','The next stage is to examine the idea with more care. What exactly was demonstrated? What is being claimed? Which conditions were present, and which conditions would be different in ordinary use? Those questions make enthusiasm more useful rather than removing it.'),
  sec('A product lives in a system','My later Money20/20 reflection added attention to identity, security, reliability, and infrastructure. The UNESCO forum added governance and accountability. Together, these experiences made it easier to see that a capability operates within a wider setting.','A product needs a setting in which people can use it. I want to understand the intended user, the organisation around the service, and the conditions it depends on. Those things are less visible than a demonstration, but they help explain why an interesting idea may be easy or difficult to put into everyday life.'),
  sec('The role of practical experience','In my later post about CEER, I was interested in user experience and design around real-world needs. That theme connects to the technology events: innovation becomes more meaningful when its purpose is clear. The question is not only whether something is new, but what it helps a person do.','I want to develop that commercial curiosity alongside my interest in the technology itself. What does a person need from the product, and why has the company chosen this approach? Asking those questions makes the idea easier to examine and gives me a more useful direction for further reading.'),
  sec('Turning an impression into a useful note','For my next reflection, I would like to distinguish what I saw, what the company said, what I could check elsewhere, and what I still do not understand. That would help me organise the thought more clearly. It also gives the excitement a useful next step: something specific to investigate.','I want to keep that curiosity while becoming more careful in how I explain it. A technology can be interesting without every possible use becoming inevitable. The question I want to follow is what needs to happen between the demonstration and the ordinary day when someone depends on the product.')]),
 ('resilience','Progress needs a method, not a mood.','learning','7488068034067333121',[
  sec('A lesson from the course reflection','After completing Resilience: Thriving as an Entrepreneur, I wrote about resilience as a skill to build. My post described focusing on what can be controlled, treating failure as feedback, adapting when plans change, and recognising small wins.','The idea is relevant to my present stage because the journey ahead is long and uncertain. A clear ambition does not remove difficult academic work or guarantee that a particular route will be available. I want to become better at responding usefully when the next step needs revision.'),
  sec('What is within my control?','The question I want to carry into a setback is concrete: which part can I improve now? Sometimes the useful action is more practice, sometimes better information, and sometimes a change to the plan. That is more productive than allowing one outcome to define the whole direction.','I can put that idea to work in school now. A difficult problem or a disappointing attempt gives me something to review: the method I used, the information I missed, and the part I can change. I want to become better at choosing the next useful action instead of making one outcome feel final.'),
  sec('A routine that supports the next task','My original post also mentioned personal well-being. A method of working should support continued effort, rather than produce one impressive day followed by an approach that cannot be maintained. I want to notice whether my habits make the next task easier to begin.','The small-wins idea is useful when the goal is distant. A completed reading note, a clearer explanation, or a better attempt at a difficult problem can provide evidence of progress. The evidence matters more than a temporary feeling of motivation.'),
  sec('From a broad lesson to an actual review','A useful review of a difficult task asks what happened, what information was missing, what was controllable, and what should change in the next attempt. That makes the lesson practical and gives the next action a reason.','I want to test the lesson through the work in front of me. After a difficult task, I can ask what happened and choose one improvement for the next attempt. A method like that makes progress easier to recognise, because it turns a broad idea about resilience into a decision I can actually make.')]),
 ('personalised-learning','A better route through scattered information.','learning,technology','7463344871580381184',[
  sec('An interest in how learning is organised','I joined YARRA among its first thousand members because I was interested in its personalised crash-course approach. The appeal was having a route through a topic instead of spending so much time moving between scattered resources. I wanted to see how a more organised introduction might help me begin learning something unfamiliar.','I shared that interest as an early user, including a referral link in the original post. What attracted me was the approach to learning: give someone a starting point and a clearer sequence to follow. It made me think about what organisation can help with, and what the learner still needs to do themselves.'),
  sec('Structure and understanding are different','A structured route can make it easier to begin a subject, but I want to distinguish an organised explanation from an established understanding. The useful question is what I can explain, apply, or check after the material has been presented.','That connects to my short courses too. Finishing material gives me a milestone, but I want to ask what I can explain afterwards. Which parts make sense? Which still feel unfamiliar? Trying an actual task is a more useful next step than assuming that an organised explanation has automatically become understanding.'),
  sec('The responsibility of checking information','AI-supported learning makes source evaluation especially relevant. A clear explanation can still need verification. I want to develop the habit of checking where a claim comes from and noticing whether the source actually supports the conclusion.','This is also relevant to my intended legal direction, where careful reading and well-supported explanation are skills I want to strengthen. A useful tool can support the process, but it does not remove the learner’s need to think critically about the material.'),
  sec('What I want from a learning tool','What I want from a tool is a clearer way to begin, while keeping room to question and check what I am reading. An appealing format can help me approach a subject, but I still need to think about the material. I am interested in the learning that happens after the explanation, not only the explanation itself.','The habit I want to develop is simple: use the structure to get started, then try to explain or apply the idea without leaning on it. That helps me see which parts I understand and where I need another explanation. It gives a tool a useful place in the process without making it the whole process.')])]
 for name,title,tags,id,sections in essays:
  add('journal/'+name+'.html',title,'Journal','My thoughts on '+{'commercial-design':'user experience and the commercial purpose of innovation','ai-governance':'capability, governance, and responsibility','agentic-commerce':'identity and authorisation in AI-enabled commerce','human-cities':'the human purpose behind development','innovation':'moving innovation from a demonstration into use','resilience':'learning through setbacks and steady progress','personalised-learning':'structure, tools, and the work of understanding'}[name]+'.',sections,tags=tags,label='Field note · Student reflection',source=post(id),source_label='Read my original post',source_note='Where this reflection began',source_description='This essay grew from the original post linked below. I have expanded the thought here as part of my own learning and writing.',related=['journal.html','events.html','direction.html'])

 add('experience/graduation.html','Supporting someone else’s milestone.','Experience','Student volunteering at the AIS graduation ceremony in May 2025.',[
  sec('Helping at the ceremony','I served as a Student Volunteer at Al-Rowad International Schools in May 2025. I assisted at a student graduation ceremony with event coordination, guest seating, logistics, setup, attendee guidance, and backstage operations.',"I helped staff and students with the programme, taking on the seating, setup, guidance, and backstage tasks described here. I liked being able to contribute to someone else's milestone. It was a reminder that doing an ordinary task carefully can make a meaningful difference to the people relying on it."),
  sec('Small tasks within a wider programme','A graduation ceremony matters to the students and people attending it. Supporting that experience involves attention to immediate tasks and to how those tasks fit the flow of the day. Seating, setup, and backstage assistance are different duties, but each contributes to a shared result.','The experience gives a concrete setting for my interest in coordination. Helping an attendee, supporting staff, or preparing part of the event is useful because someone else depends on it. Responsibility begins with doing that task clearly and reliably.'),
  sec('Communication as a practical activity','The ceremony gave me something concrete to think about when considering communication. The useful question was not whether I could describe myself as a good communicator; it was whether someone understood the guidance and knew what to do next. That is the kind of clarity I want to practise in future teamwork.','The broader development goal is to improve how I give and receive information. A task can become harder when its purpose or next step is unclear. I want to carry attention to clarity into future teamwork, academic projects, and appropriate professional learning experiences.'),
  sec('What I want to build on','The volunteering connects to my interest in how organisations work. A programme depends on separate people understanding their responsibilities and supporting one another. I enjoyed seeing that on a school occasion, where the importance of the day was clear to the students and families attending it.','I would like to build on the experience through new tasks and responsibilities that fit my stage. Helping with something useful, understanding why it matters, and learning how to do it better would give me more to carry forward. I want future experiences to develop the habit of contributing carefully, even when the task is small.')
 ],source=PROFILE,source_label='Connect with me',label='Al-Rowad International Schools · May 2025',date='May 2025',facts=[('Role','Student Volunteer'),('Organisation','Al-Rowad International Schools'),('Setting','Student graduation ceremony'),('When','May 2025 · one month')],related=['experience.html','skills/communication.html','about.html'])
 add('projects/portfolio.html','Bringing my story together.','Projects','The original portfolio website: an AI-assisted project in content, organisation, and useful interaction.',[
  sec('The problem to solve','I wanted a personal website that connected my interests instead of leaving them as separate lists. School, courses, languages, event visits, and future plans all contribute to the direction I am taking. The brief was to bring them together in a detailed portfolio that felt formal, expressive, and recognisably personal.','The result lets someone start with my background, follow a subject that interests them, or spend more time with a particular reflection. I wanted the connections to be easy to follow. A course, an experience, and a future interest can tell a more useful story together than each would on its own.'),
  sec('Giving each subject room','There are separate chapters for my education, direction, learning, languages, experiences, events, writing, and projects. I wanted enough room to explain why something interested me, not just name it. Course pages include certificates; language pages explain where I am with each language; event pages describe the questions I carried away.','The journal gives those questions more space. I linked the essays to the posts that began them, and connected related courses and experiences where they share a theme. That makes the writing easier to explore and helps me see how an interest has changed as I encountered it in different settings.'),
  sec('Motion and interaction with a purpose','The homepage follows curiosity, perspective, and direction through a scroll sequence. Search and topic filters offer another way to explore, while long pages can be read as a guided story, an essay, or a quick overview. I wanted the motion and the reading options to help someone find their own path through the site.',"The contact composer prepares a draft for the visitor's email app, where they can review the wording and choose to send it. It also offers a copyable draft when needed. I wanted the interaction to be clear and useful, with the person keeping control of the actual message."),
  sec('Attribution and the next iteration','I created the site with AI-assisted development, shaped by my design brief, personal information, and feedback. I wanted warmth and movement without losing a formal tone. Bringing those aims together involved thinking about the writing, the structure, and the experience of moving through the pages on different screens.','I want the website to grow through new experiences and better writing. If I add something, there should be a reason for it: a question worth exploring, a useful example, or a clearer way to explain an interest. That is more appealing to me than adding a feature simply because it is possible.')
 ],label='Original website · 2026',related=['projects.html','skills/systems.html','journal.html'])
