def populate_experiences(add,sec,PROFILE):
 def post(id):return 'https://www.linkedin.com/feed/update/urn:li:activity:'+id+'/'
 events=[
 ('unesco','When the conversation became about responsibility.','UNESCO Global Forum on the Ethics of AI','September 2026','governance,technology','7505991669549256705',[
  sec('What I expected, and what changed','I attended the fourth UNESCO Global Forum on the Ethics of AI in Riyadh. My LinkedIn reflection begins with an expectation: I thought it would be closer to a large technology exhibition, with products, companies, and new capabilities on display. The experience was different. The conversations centred on what people and institutions are going to do with those capabilities.','I found myself listening to governments, researchers, international organisations, and people working on governance. The shift mattered because it moved the subject from technical possibility to responsibility. A system doing something impressive is only the beginning of a much wider set of questions.'),
  sec('The questions that stayed','In my post, I asked who is responsible when AI causes harm, how humans remain accountable when decisions involve machines, and how governments approach systems that operate across borders. I also noticed the discussion of environmental and energy demands.','The value of the event was not that it supplied one final answer. It showed me how many perspectives are involved and how implementation becomes part of the discussion. I left with a more concrete interest in the relationship between innovation, institutions, and the rules around them.'),
  sec('Learning through conversations','Some of the moments I valued most were conversations with people from different countries and backgrounds. I wrote that these exchanges made it clearer that there is no single universal perspective on AI: different settings bring different opportunities, risks, and priorities.','That was a useful reminder to listen before simplifying a subject. A policy discussion or business decision can look different when the assumptions and conditions behind it change. I want to carry that attention into my own reading and writing.'),
  sec('Connection to my current direction','As someone aspiring towards corporate law, I began looking at the forum through questions of responsibility, risk, data, and decision-making. This is a developing student perspective, rather than a claim of professional AI governance expertise.','The related journal essay develops the central question: what comes after a technology becomes capable of performing a task? The original post remains linked so readers can see the experience that prompted the reflection.')], 'unesco.jpg'),
 ('money2020','Identity behind the transaction.','Money20/20 Middle East','September 2026','technology,business','7505617162829545472',[
  sec('More technology than I expected','I attended Money20/20 Middle East in Riyadh, initially expecting a finance-heavy event focused on banking and payments. In my post, I described finding a much wider technology conversation: AI, agentic AI, cybersecurity, digital identity, authentication, and the infrastructure around them.','That changed what I paid attention to. The subject was not simply what a technology could demonstrate, but what companies were building in order to use it. The exhibition brought several connected industries into one view and made their overlap easier to recognise.'),
  sec('The agentic commerce question','One session that interested me concerned AI agents taking actions for people. My reflection asked how a company would know that an agent was authorised to make a purchase or carry out a transaction, how identity would be established, and how much control a person should retain.','Those questions made an abstract development concrete. The ability to perform an action is different from knowing that the action is appropriate and authorised. I want to investigate that distinction further as part of learning about business, technology, and responsibility.'),
  sec('From pilots to products','Another discussion concerned moving AI from pilots into actual products. In my post, I connected this to data, security, reliability, and infrastructure. The point that stayed with me was the gap between demonstrating a capability and relying on it in a real operating environment.','This also connected to the other events I had attended. LEAP offered a broad view of innovation; Black Hat MEA provided cybersecurity exposure. Money20/20 showed another part of the same ecosystem, through financial services and the systems that make transactions possible.'),
  sec('A developing commercial lens','I left thinking more about AI, security, and identity than I had expected. For my current interest in corporate law, the experience offers questions worth pursuing about how organisations make technology useful and how responsibilities are understood.','This page records my attendance and the themes in my source post. It does not imply employment in financial services or professional expertise in payment systems. The related essay expands the authorisation question as a student reflection.')], 'money2020.jpg'),
 ('leap','Seeing an idea move towards everyday life.','LEAP Riyadh','2026','technology','7501288436100923392',[
  sec('An exhibition that widened the view','My LinkedIn post records attending LEAP in Riyadh in 2026. I described seeing technologies associated with AI, autonomous transport, robotics, delivery systems, and new ways of interacting with services. The experience made developments I had followed more tangible.','The post was enthusiastic about what might change in everyday life. In this portfolio, I keep that enthusiasm in context: an exhibition offers exposure to demonstrations and company claims, rather than proof that every proposed use is already widely available or commercially established.'),
  sec('The difference between seeing and understanding','The useful next question is what it takes for a demonstration to become a service people can depend on. A product needs more than an impressive moment on a stand. I want to understand the surrounding organisation, the intended user, the practical constraints, and the evidence behind a claim.','That perspective helps me revisit the event more carefully. Instead of treating every possibility as inevitable, I can ask which assumptions support it and what information would be needed to assess progress. This is part of developing better commercial and technical reading habits.'),
  sec('A personal part of the day','I also wrote about trying an F1 simulator and learning more about the Saudi Arabian Grand Prix. That was a different part of the visit and reflects the breadth of interests an event can bring together. It belongs in the record as a personal experience, not a motorsport qualification.','The wider impression was of ideas moving closer to practical use. My later Money20/20 and UNESCO reflections added another layer by focusing on identity, implementation, governance, and accountability around those capabilities.'),
  sec('What I want to carry forward','LEAP belongs to the technology chapter of my learning record. Its value is in the questions it prompted and the opportunity to encounter products and discussions firsthand. My present legal ambition gives those observations a new commercial context.','The related journal page explores the gap between a demonstration and dependable use. It keeps a student’s curiosity visible while avoiding unsupported predictions about when a technology will replace an existing service or become part of everyday life.')],None),
 ('airports','The coordination you do not see.','Global Airports Forum','2025','aviation,business','7406670810586828802',[
  sec('A different understanding of airports','I attended the Global Airports Forum in Riyadh and wrote that it changed how I looked at airports. From the outside, terminals, runways, and aircraft movements can seem calm and routine. The discussions drew my attention to the decisions and dependencies behind that appearance.','My post used a small boarding delay as an example. What looks minor to a passenger can connect to gate availability, crew duty time, aircraft rotations, baggage sequencing, and wider coordination. I was interested in how one change can affect several parts of the operation.'),
  sec('Learning from people in the industry','My reflection records meeting aviation professionals and executives, including Omar al Hosari, David Buczek, and Julius Norkunas. I valued hearing about their experiences and their views on airport operations and strategy.','These were conversations at an industry event. They are not presented as professional appointments, formal mentoring arrangements, or organisational affiliations. Their importance to me was the opportunity to hear perspectives from people working in a field I was exploring.'),
  sec('Technology within the operation','I also wrote about the role of AI in airport management and the different ways technology was being discussed. The broader observation was how many systems, teams, and decisions need to work together for the passenger journey to feel straightforward.','That interest in invisible coordination remains relevant even though my career direction has changed. I want to understand what an organisation depends on to deliver its service, and how a result that looks simple can rest on a complex system.'),
  sec('An earlier ambition in its proper context','At the time of the source post, I was working towards an aviation ambition. My current focus is corporate and commercial law. Keeping both contexts clear makes the progression more accurate than rewriting an older experience to sound as if the present direction had always been fixed.','This event connects to my aviation courses and to the systems capability page. It represents participation and learning, not employment in airport operations or evidence of pilot training.')],None),
 ('blackhat','A closer look at digital trust.','Black Hat Middle East & Africa','2025','technology','7402361128523280384',[
  sec('Encountering the security perspective','My LinkedIn post records attending Black Hat MEA 2025. I described sessions and discussions about emerging threats, defence strategies, and the direction of technology in the Middle East. The event added a security perspective to interests I had previously explored through aviation and technology.','That wider exposure matters because a digital service is not only defined by what its interface allows a user to do. I want to understand the systems and decisions that support trust in its use. The event gave me another set of questions to pursue.'),
  sec('The CPD activity in my record','In the same post, I reported completing ten hours of CPD activities and receiving a certificate accredited with ten CPD credits. This portfolio identifies that as a profile-reported activity and links to the original post. The certificate itself has not been independently audited here.','The activity should not be confused with a professional cybersecurity qualification or an authorisation to carry out security testing. It records participation in learning activities at the event, with the limits of that evidence kept visible.'),
  sec('Connections to later experiences','Cybersecurity themes appeared again in my Money20/20 reflection, alongside identity, authentication, and infrastructure. Seeing those topics in different settings made it easier to recognise how they connect to the way organisations use technology.','My current corporate-law ambition gives that connection another relevance. I want to understand how a business thinks about a system it depends on and the responsibilities around it. Further study would be needed before those questions could support specialist conclusions.'),
  sec('A student development record','The value of this event in my portfolio is exposure, reflection, and a reported CPD activity. It shows an effort to learn beyond the classroom and a subject that connects to my broader interests. It does not establish professional practice in cybersecurity.','A useful next step is careful reading about an identified security or identity issue, with sources and a clear distinction between facts and interpretation. That would add more substantive evidence of understanding than simply repeating the event title.')],None),
 ('real-estate','Cities need people to become places.','Real Estate Future Forum','2026','business','7422345465716703233',[
  sec('A human perspective on development','My post records attending day three of the Real Estate Future Forum in Riyadh in 2026. I wrote about a discussion that moved beyond buildings and skylines towards how cities function, how communities form, and how value is experienced by the people living in them.','The themes I noticed included sustainability, density, lifestyle, and human-centred planning. What stayed with me was the idea that a physical development needs a social purpose. The experience broadened the way I thought about business and investment.'),
  sec('Ideas from the discussions','In my reflection, I referred to a point made by Peter Jonathan Jameson about the importance of people, proximity, and interaction. I also described Sir Richard Branson’s emphasis on culture, experience, and the people within a business.','These were ideas I encountered as an attendee. I do not present them as private conversations or personal professional relationships. Their relevance was to the question that emerged from the day: what makes a project meaningful beyond the physical asset?'),
  sec('Connecting commercial and human value','For my current interests, the forum offers a reminder to ask who a project is intended to serve. Investment and development can be discussed through numbers and physical outputs, but the experience of people is another part of the picture I want to understand.','That does not supply a professional assessment of an urban project. It supplies a student’s starting question and a theme for further reading. The related journal essay develops that theme as an edited expansion of the original post.'),
  sec('A wider learning context','This event sits alongside finance, technology, and governance experiences in my portfolio. Together, they encourage me to look beyond the most visible element of a subject and consider the wider organisation and purpose around it.','The page records attendance and the themes in my reflection, without claiming real estate expertise or investment experience. The source link provides the original context and allows readers to distinguish the recorded event from the broader questions developed here.')],None),
 ('sand-and-fun','The discipline behind the display.','Sand & Fun Aviation Show','2025','aviation','7399801706664062976',[
  sec('An aviation experience with several dimensions','My LinkedIn post records attending the Sand & Fun Aviation Show in Riyadh. I described exposure to aircraft, different aviation disciplines, displays, and conversations with people in the industry. It belongs to the earlier aviation chapter of my learning record.','The event was memorable for its visible performances, but the idea that stayed with me was the discipline behind them. A display can make precision look effortless. My reflection focused on the standards, technical skill, and dedication that such performances suggested.'),
  sec('What I recorded in the post','I wrote about watching Luke Czepiela land on a moving truck, aerobatic displays from several countries, a paramotor team, Royal Saudi Air Force performances, and the night programme. These are observations from my attendance, not activities in which I participated as an operator.','I keep that distinction clear because an interest in aviation and attendance at an aviation show do not establish flight experience. This portfolio does not present the event as pilot training or a professional qualification.'),
  sec('An earlier direction, a lasting question','At the time, aviation was my long-term career goal. My current direction is corporate law. The earlier experience remains useful as part of understanding how I became interested in complex systems and the people responsible for their performance.','The lasting question is what sits behind the result. What preparation makes the visible outcome possible? What standards govern the work? How do teams coordinate? Those questions connect to the broader pattern in my learning, even as the intended profession changes.'),
  sec('How this fits the portfolio','Sand & Fun connects to the crew management, aviation management, and aircraft design courses in my record. The course pages document structured learning; this page documents an industry event and the perspective it prompted.','The source post remains linked so readers can see its original aviation context. I want the portfolio to show development honestly, preserving earlier interests while keeping current ambitions and completed achievements separate.')],None),
 ('electric-mobility','A new view of how people move.','Riyadh EV Auto Show','2025','technology,business','7409623371191271424',[
  sec('The experience preserved in my annual reflection','My 2025 LinkedIn Rewind mentions experiencing electric buses at the Riyadh EV Auto Show. The annual reflection places this alongside aviation events and cybersecurity learning as an example of exploring how technology is reshaping different industries.','The available source is that retrospective post. It does not provide a detailed session record, exact visit date, or professional role at the show. This page keeps that limited evidence visible rather than inventing activities to make the event sound more substantial.'),
  sec('Mobility as a wider interest','Transport connects several parts of my learning record. Aviation first drew my attention to operations and coordination. Electric mobility adds questions about how products and services change the experience of moving people from one place to another.','I want to understand the organisation around a mobility product as well as the product itself. Who is it intended to serve? Which conditions need to be in place for it to be useful? What evidence would show that the proposed benefits are being realised? Those are questions for further study.'),
  sec('From product interest to commercial questions','My later post about CEER also reflects an interest in practical user experience and technology designed around a local setting. The connection is an attention to how innovation meets a real need, rather than a claim of automotive expertise.','My current corporate-law direction makes the commercial context more interesting. A product exists within an organisation, a market, and a set of decisions. Introductory business courses give me a starting point for asking about that context, but not a basis for a professional assessment.'),
  sec('The limits of this entry','This entry records a brief experience reported in my own annual reflection. It does not claim that I tested vehicle systems, carried out technical analysis, or worked with an exhibitor. The source link provides the level of detail actually available.','A more substantial future mobility reflection would need identifiable observations and supporting sources. For now, this page gives the event its proper place in the wider story: a point of exposure that connects transport, technology, and commercial curiosity.')],None),
 ('global-ai','An announced intention to explore AI.','Global AI Show Riyadh','2026 · announced participation','technology','7465766602609758208',[
  sec('What the source establishes','My LinkedIn activity includes an announcement that I would attend Global AI Show Riyadh on 29–30 June 2026. That is the fact this entry records. The available post is an attendance announcement rather than a detailed account of sessions, meetings, or completed activities.','Registration or an announced plan should not be used as proof of attendance. This page therefore does not invent a visit report or list outcomes that the source does not establish. It preserves the announced interest as part of the wider activity record.'),
  sec('Why the subject fits my interests','AI appears across several of my more detailed event reflections. At LEAP I encountered demonstrations and products. At Money20/20 I wrote about agentic AI, identity, and infrastructure. At the UNESCO forum I focused on responsibility and governance.','The announced Global AI Show participation belongs to that broader interest in understanding how AI is being developed and used. The completed attendance reflections elsewhere provide stronger evidence of the questions that have actually stayed with me.'),
  sec('Useful questions for future learning','For an AI event, I would want to ask what a system can demonstrate, what evidence supports its claims, and what is required before it can be used reliably. A commercial perspective also asks who needs the product and what problem it is intended to solve.','Those are learning questions, not conclusions about the exhibitors or programme at this event. They explain why the subject interests me without implying that I attended particular sessions or assessed a company’s technology.'),
  sec('Keeping the portfolio accurate','The event hub distinguishes announcements from attendance reflections. That makes the record more useful for a reader trying to understand what I have done and what I have expressed interest in doing.','The source announcement is linked below. If a detailed attendance record becomes available, this entry can be expanded with that evidence. Until then, its purpose is to preserve the actual activity in context, with the limits of the available information stated clearly.')],None),
 ('global-games','An interest in the technology of games.','Global Games Show Riyadh','2026 · announced participation','technology,business','7464961205401497602',[
  sec('An announcement in the activity record','My LinkedIn activity includes an announcement of planned attendance at Global Games Show Riyadh on 29–30 June 2026. The available post gives an event and an intended participation, rather than a detailed account of what I saw or did.','This page therefore records the announcement without treating it as independently established attendance. It does not invent sessions, exhibitor conversations, project work, or professional involvement in the gaming industry.'),
  sec('Where the interest connects','My wider portfolio includes Computer Science study, technology events, and business learning. A games event sits at an intersection of those interests, where a digital product can be considered through both the technology behind it and the experience of the people using it.','That connection gives a reason for the announced interest, but it does not prove specialist game development or esports experience. I want the portfolio to distinguish curiosity about a field from the evidence needed to claim competence within it.'),
  sec('Questions worth exploring','A useful learning question is how a product’s design serves its intended user. What makes the experience understandable? Which decisions help someone begin using it? What would need to work together for that experience to be reliable?','A commercial perspective adds another set of questions about audience, value, and the organisation around a product. My business courses are introductory context for that perspective. These questions are a direction for future learning, not findings from unrecorded activities at this event.'),
  sec('The record and the next update','The original announcement remains linked below so that its evidence can be read directly. More detailed event reflections elsewhere in the portfolio demonstrate a different kind of record: attendance followed by specific observations.','If a future update provides concrete evidence from this event, the page can develop accordingly. At present, it accurately preserves an announced interest in gaming and technology while keeping the absence of a detailed attendance report visible.')],None)
 ]
 for name,title,event,date,tags,id,sections,image in events:
  kw={}
  if image:kw={'image':image,'image_alt':('Stage screen at the UNESCO Global Forum on the Ethics of AI in Riyadh'if image=='unesco.jpg'else 'Money20/20 Middle East event photograph from my LinkedIn post'),'image_caption':'Photograph from my original event post on LinkedIn.'}
  add('events/'+name+'.html',title,'Events',event+' · '+('An announced interest, with the source limits kept visible.'if 'announced'in date else 'An attendance reflection and the questions it prompted.'),sections,date=date,label=event,tags=tags,source=post(id),source_label='Read the original post',source_note='Source and editorial context',source_description='This page expands the themes of my original LinkedIn post. Specific activities are limited to what the source records; broader paragraphs provide student learning context.',evidence_type='Announcement'if 'announced'in date else 'Personal event record',related=['events.html','journal.html','skills/systems.html'],**kw)

 essays=[
 ('commercial-design','Innovation should remember the person.','technology,business','7507880159203504128',[
  sec('A detail that changed the emphasis','My post about CEER’s EXOBOT models focused on innovation designed around practical needs. I was interested in the relationship between advanced technology and the experience of the person using a product. The commercial question was not simply how much technology could be added, but which decisions made it useful.','That perspective connects to the events I have attended. A demonstration can make a new capability visible. Understanding a product requires asking what problem it is meant to solve and how the design fits the conditions in which someone will use it.'),
  sec('Keeping the user in the picture','In the source post, I wrote about cabin comfort in Saudi Arabia’s climate and the value of retaining physical controls for essential functions. Those details interested me because they brought the conversation back to an ordinary person interacting with a product.','This essay does not reproduce performance specifications as independently verified facts. It records the design themes that caught my attention and the wider question they prompted. My role is that of a student reading a product announcement, rather than a technical reviewer who has tested the vehicles.'),
  sec('A commercial perspective worth developing','A useful next question is how a company understands the needs of its intended audience. Which features answer an actual problem? What trade-offs are being made? What information would help a reader judge whether the proposed benefit has been demonstrated?','My sales, administration, and finance courses provide introductory context for asking those questions. They do not settle them. I want to develop the habit of separating a company’s stated intention, the available evidence, and the interpretation I am making from that information.'),
  sec('The connection to my direction','My current interest in corporate law includes understanding businesses as organisations making decisions. A product announcement offers one small window into that work: an ambition, an intended customer, a practical setting, and assumptions about what will create value.','The lesson I want to carry forward is to keep the person in the picture when thinking about innovation. This is an edited expansion of my original post, not a professional automotive assessment or a recommendation to purchase a product. It preserves a question I want to investigate more carefully.')]),
 ('ai-governance','The question after capability.','technology','7505991669549256705',[
  sec('What happens after it works?','I went to the UNESCO Global Forum on the Ethics of AI expecting to see more of what technology could do. Instead, I found myself thinking about what happens after a system becomes capable of doing something. That was the central shift in my original reflection.','A demonstration can create excitement, but capability does not finish the conversation. My questions became about responsibility, human accountability, the role of institutions, and how broad ideas are put into practice. The experience changed the lens through which I wanted to look at AI.'),
  sec('The setting changes the question','Conversations with people from different countries and backgrounds were among the parts I valued most. I wrote that they made it easier to see why there is no single universal perspective on AI. Different settings bring different priorities and different conditions.','That observation matters to how I want to learn. A simple description can leave out the assumptions that make a position understandable. Before deciding that one answer applies everywhere, I want to ask whose circumstances are being considered and what information is missing.'),
  sec('Principles need a practical route','My reflection also focused on implementation. It is one thing to express a broad goal; it is another to decide how an organisation will act on it. I want to understand the people, processes, and information needed to make that step useful.','These are questions that connect to my interest in corporate law. Businesses adopt technology within a wider setting of responsibilities and decisions. Understanding that setting requires more than following the most impressive feature of a new system.'),
  sec('A student’s next step','The next useful task is careful research on one identifiable question, with sources and limits made explicit. I want to become better at separating an observation, an interpretation, and a conclusion that stronger evidence would be needed to support.','This essay is an edited expansion of my event post, not legal advice or a professional governance assessment. Its value is the question it preserves: once a system can do something, what needs to be understood before people can rely on it?')]),
 ('agentic-commerce','An action needs more than an instruction.','technology,business','7505617162829545472',[
  sec('The question that made AI concrete','At Money20/20 Middle East, I was interested in discussions of agentic commerce: AI systems taking actions for people. My original post asked how a company knows an action is authorised, how identity is established, and how much control the person should have.','Those questions stayed because they connected technology to an ordinary action, such as making a purchase. Performing the task is not the whole problem. The surrounding system needs a way to understand the relationship between the person, the agent, and the action.'),
  sec('Beyond the impressive demonstration','The event also included a discussion of moving AI from pilots into actual products. I wrote about data, security, reliability, and infrastructure as part of that transition. The distinction between a demonstration and something an organisation relies on became more important to me.','That does not establish the answer to a technical or legal problem. It gives a student a useful set of questions: what assumptions does the system depend on, what happens when a condition changes, and what information would help someone evaluate the result?'),
  sec('Connected industries, connected questions','Walking through the exhibition brought AI, cybersecurity, identity, payments, banking, and infrastructure into one view. I connected the experience to LEAP and Black Hat MEA, which had shown different parts of the same wider technology landscape.','The commercial perspective I want to develop involves recognising those connections without flattening the differences between subjects. A company adopting a tool may depend on several systems around it, and each deserves more careful study than an event summary can provide.'),
  sec('What I want to investigate next','A useful next exercise would be to trace one proposed agent action and identify the open questions at each step. Who requests it? What permission is given? What can the person review? Which information would show what happened?','That would be a learning exercise, not a design recommendation or a legal assessment of an existing product. The point is to improve the quality of the question. My original post provides the experience that prompted it, and the portfolio keeps that source context visible.')]),
 ('human-cities','An asset becomes a place through people.','business','7422345465716703233',[
  sec('Looking beyond the skyline','At the Real Estate Future Forum, I noticed a discussion that moved beyond constructing buildings towards how people live, work, and connect. My original reflection focused on the human element of development and the experience that turns a physical asset into a meaningful place.','That idea resonated because it challenged the most visible way of looking at real estate. A skyline can be impressive, but the question I wanted to ask was what the development makes possible for the people who use it.'),
  sec('Value with a wider context','My post referred to ideas about density, proximity, interaction, culture, and experience. These are different perspectives, yet they all point towards the purpose surrounding the physical result. I want to understand how commercial objectives connect to that lived context.','This is a student reflection rather than a professional view of urban planning or real estate investment. The event did not make me qualified to assess a project. It made a question more visible: whose needs give the project its meaning?'),
  sec('The connection to business','The same question can be useful when looking at a business. A product, service, or investment is part of a wider relationship with the people it is intended to serve. Understanding its stated purpose should include understanding that relationship.','My introductory administration, finance, and sales learning provide starting points for this perspective. They encourage me to look at a company from more than one angle, while recognising that a serious assessment requires more evidence and deeper knowledge.'),
  sec('A habit for future reading','When reading a development announcement, I want to separate the physical proposal, the commercial objective, and the claimed benefit to people. What information supports each part? Which assumptions remain open? What would show that the result serves its intended purpose?','This essay expands the theme of my original event post. It does not claim private access to the speakers or first-hand expertise in development projects. It records a useful change in perspective and a question I want to carry into further commercial learning.')]),
 ('innovation','The distance between a demo and daily life.','technology','7501288436100923392',[
  sec('The excitement of seeing something work','My LEAP post was enthusiastic about technologies that made the future feel close. Seeing a product or demonstration in person can make an idea much more tangible than reading about it. That excitement belongs in the record because it explains why I wanted to learn more.','The next stage is to examine the idea with more care. What exactly was demonstrated? What is being claimed? Which conditions were present, and which conditions would be different in ordinary use? Those questions make enthusiasm more useful rather than removing it.'),
  sec('A product lives in a system','My later Money20/20 reflection added attention to identity, security, reliability, and infrastructure. The UNESCO forum added governance and accountability. Together, these experiences made it easier to see that a capability operates within a wider setting.','I want to understand that setting before assuming a demonstration predicts everyday adoption. A company’s product, its intended user, its processes, and the information supporting its claims all deserve consideration. A short visit to an exhibition cannot settle every part of that picture.'),
  sec('The role of practical experience','In my later post about CEER, I was interested in user experience and design around real-world needs. That theme connects to the technology events: innovation becomes more meaningful when its purpose is clear. The question is not only whether something is new, but what it helps a person do.','This is a commercial curiosity I want to develop. It is not a technical evaluation of the products mentioned in my posts, and I have not reproduced unverified performance specifications as established facts in this essay.'),
  sec('Turning an impression into a useful note','A practical research note could separate four things: what I observed, what the company said, what an independent source establishes, and what remains uncertain. That structure would make the next reflection clearer and less dependent on an initial impression.','This essay is an edited expansion of my LEAP reflection, with the same curiosity and a more careful set of questions. It records how my perspective is developing rather than offering a forecast of when a technology will become widely used.')]),
 ('resilience','Progress needs a method, not a mood.','learning','7488068034067333121',[
  sec('A lesson from the course reflection','After completing Resilience: Thriving as an Entrepreneur, I wrote about resilience as a skill to build. My post described focusing on what can be controlled, treating failure as feedback, adapting when plans change, and recognising small wins.','The idea is relevant to my present stage because the journey ahead is long and uncertain. A clear ambition does not remove difficult academic work or guarantee that a particular route will be available. I want to become better at responding usefully when the next step needs revision.'),
  sec('What is within my control?','The question I want to carry into a setback is concrete: which part can I improve now? Sometimes the useful action is more practice, sometimes better information, and sometimes a change to the plan. That is more productive than allowing one outcome to define the whole direction.','This is a reflection on learning, not a claim that I have managed a business through a crisis. My course record remains attached to the context in which the lesson was introduced, and my current experience is that of a school student.'),
  sec('A routine that supports the next task','My original post also mentioned personal well-being. A method of working should support continued effort, rather than produce one impressive day followed by an approach that cannot be maintained. I want to notice whether my habits make the next task easier to begin.','The small-wins idea is useful when the goal is distant. A completed reading note, a clearer explanation, or a better attempt at a difficult problem can provide evidence of progress. The evidence matters more than a temporary feeling of motivation.'),
  sec('From a broad lesson to an actual review','A useful review of a difficult task asks what happened, what information was missing, what was controllable, and what should change in the next attempt. That makes the lesson practical and gives the next action a reason.','This essay expands my course completion post as a student reflection. It does not offer psychological advice. Its purpose is to preserve a development principle in a form I can test through academic work and future learning experiences.')]),
 ('personalised-learning','A better route through scattered information.','learning,technology','7463344871580381184',[
  sec('An interest in how learning is organised','My post about YARRA describes being among its first thousand members and being interested in a personalised crash-course approach. The appeal I recorded was the possibility of organising learning around a topic, rather than spending time moving between scattered resources.','This page records that personal interest. It is not presented as employment, investment, a partnership, or participation in building the platform. The source post expresses an early user’s enthusiasm and contains a referral link.'),
  sec('Structure and understanding are different','A structured route can make it easier to begin a subject, but I want to distinguish an organised explanation from an established understanding. The useful question is what I can explain, apply, or check after the material has been presented.','That perspective connects to the learning record elsewhere in this portfolio. Course completion provides a concrete milestone; the next step is to identify what the subject introduced, what remains unclear, and which task would provide better evidence of understanding.'),
  sec('The responsibility of checking information','AI-supported learning makes source evaluation especially relevant. A clear explanation can still need verification. I want to develop the habit of checking where a claim comes from and noticing whether the source actually supports the conclusion.','This is also relevant to my intended legal direction, where careful reading and well-supported explanation are skills I want to strengthen. A useful tool can support the process, but it does not remove the learner’s need to think critically about the material.'),
  sec('Keeping the record proportionate','The source post records early membership and an interest in the product. It does not establish that the platform has delivered the wider outcomes I hoped it might. I have not reproduced those hopes as confirmed product claims in this portfolio.','The lesson for my own development is to use structure as a starting point, then test understanding through an actual task. That keeps the focus on learning rather than on accumulating the appearance of progress.')])]
 for name,title,tags,id,sections in essays:
  add('journal/'+name+'.html',title,'Journal','An edited reflection on '+{'commercial-design':'user experience and the commercial purpose of innovation','ai-governance':'capability, governance, and responsibility','agentic-commerce':'identity and authorisation in AI-enabled commerce','human-cities':'the human purpose behind development','innovation':'moving innovation from a demonstration into use','resilience':'learning through setbacks and steady progress','personalised-learning':'structure, tools, and the work of understanding'}[name]+'.',sections,tags=tags,label='Field note · Student reflection',source=post(id),source_label='Read the source post',source_note='An edited adaptation',source_description='This essay expands a theme from my original LinkedIn post. It is a student reflection, not professional advice, a technical audit, or a verified forecast.',related=['journal.html','events.html','direction.html'])

 add('experience/graduation.html','Supporting someone else’s milestone.','Experience','Student volunteering at the AIS graduation ceremony in May 2025.',[
  sec('The role in the record','My LinkedIn profile records a Student Volunteer role at Al-Rowad International Schools in May 2025. I assisted at a student graduation ceremony with event coordination, guest seating, logistics, setup, attendee guidance, and backstage operations.','The role was a contribution to the programme, rather than overall responsibility for organising it. I helped staff and students with the tasks described in the profile. That practical distinction is important to how the experience is presented here.'),
  sec('Small tasks within a wider programme','A graduation ceremony matters to the students and people attending it. Supporting that experience involves attention to immediate tasks and to how those tasks fit the flow of the day. Seating, setup, and backstage assistance are different duties, but each contributes to a shared result.','The experience gives a concrete setting for my interest in coordination. Helping an attendee, supporting staff, or preparing part of the event is useful because someone else depends on it. Responsibility begins with doing that task clearly and reliably.'),
  sec('Communication as a practical activity','This record supports the communication capability page more directly than a general claim of being a strong communicator would. It identifies a setting, a role, and actual duties. A reader can understand what kind of activity the claim refers to.','The broader development goal is to improve how I give and receive information. A task can become harder when its purpose or next step is unclear. I want to carry attention to clarity into future teamwork, academic projects, and appropriate professional learning experiences.'),
  sec('What I want to build on','This is school volunteering, not employment within a law firm or professional event management experience. It belongs in the portfolio as an early practical contribution and a point of connection to the organisational themes in my learning.','The next useful experiences would add new responsibilities and observable work. I want future entries to explain the setting, what I actually did, and what evidence supports the record, rather than simply add a more impressive title to the same activities.')
 ],source=PROFILE,source_label='View volunteering on my profile',label='Al-Rowad International Schools · May 2025',date='May 2025',facts=[('Role','Student Volunteer'),('Organisation','Al-Rowad International Schools'),('Setting','Student graduation ceremony'),('Recorded period','May 2025 · one month')],related=['experience.html','skills/communication.html','about.html'])
 add('projects/portfolio.html','A personal record, made navigable.','Projects','The original portfolio website: an AI-assisted project in content, organisation, and useful interaction.',[
  sec('The problem to solve','A LinkedIn profile holds valuable information, but its sections do not always show how an experience connects to a wider direction. Courses, languages, event reflections, and ambitions can appear as separate entries. The project brief was to create a detailed personal portfolio with distinct pages and a formal but expressive presentation.','This site begins with that problem. Its architecture lets a visitor start with the person, inspect evidence, or follow a theme across several chapters. The aim is to add context, not simply reproduce the profile in a different colour.'),
  sec('A structure built around the record','The portfolio includes biography, education, journey, direction, capabilities, learning, languages, experiences, events, journal, projects, and contact chapters. Course pages preserve issue dates and credential links. Language pages keep the individual proficiency levels clear. Event pages distinguish attendance reflections from announcements.','The journal gives ideas more space, while links connect each adapted reflection to its original post. Duplicate course entries from the profile’s honours section are consolidated rather than counted as additional achievements.'),
  sec('Motion and interaction with a purpose','The homepage follows curiosity, perspective, and direction through a scroll sequence. An unpinned layout keeps the chapters readable on short viewports. Search and topic filters help visitors move through the record, and long pages offer both a quick scan and a full story.','The contact composer prepares an email draft for the reader to review and send. It does not imply that an unconnected service has delivered a message. These interactions are intended to make the site useful as well as expressive.'),
  sec('Attribution and the next iteration','The site was created with AI-assisted development. It is not presented as proof that I independently wrote every line of its code. My role is reflected in the purpose, the design brief, the personal record, and the standards the site aims to communicate.','Future improvement should follow new evidence and actual visitor needs. New experiences, stronger writing, and clearer examples would add more value than features added only for novelty. The source remains editable so that the record can develop alongside the person it represents.')
 ],label='Original website · 2026',related=['projects.html','skills/systems.html','journal.html'])
